extends Node
## Bit-exact gate for `AxieToDie` against the live JS `axieToDie()`.
##
## WHY BIT-EXACT AND NOT "ROUGHLY RIGHT"
## -------------------------------------
## `src/engine.js:118` carries a BLOCKING invariant: this algorithm is pure, because
## `api/submit-run.js` replays a ranked run on the server and has to rebuild the SAME die from
## the same part data. If the Godot port drifts by one point on one face, an imported Axie plays
## differently here than the score a server would compute — and nothing throws. The whole failure
## is a number quietly being wrong.
##
## So the reference is not hand-written expectations: `axie_to_die_reference.json` is GENERATED by
## running the real `src/engine.js` over ten fixtures. Regenerate it, never hand-edit it; a
## hand-tuned expectation is just this file agreeing with itself.
##
## The fixtures are built from real catalogue keys so every branch is exercised: signature faces,
## variant faces, the unmapped-part fallback, the blank fallback, short dice, the "α" stage
## suffix, Origin (Dawn) class collapse, gene tiers 0/2/6, an unrecognised class, and no parts.
##
## FIELD NAMES DIFFER ON PURPOSE. JS returns `hp`/`axieId`/`secretCls`/`geneTier`; this port
## returns `max_hp`/`axie_id`/`secret_cls`/`gene_tier` to match the roster shape the rest of the
## Godot code already uses. The mapping is declared below, so a rename is a visible edit here
## rather than a silent mismatch.
##
## Run: godot --headless --path godot res://tests/t_axie_to_die.tscn

const REFERENCE_PATH := "res://tests/axie_to_die_reference.json"

## js field -> gdscript field, where they intentionally differ.
const RENAMED := {"hp": "max_hp", "axieId": "axie_id", "secretCls": "secret_cls",
	"geneTier": "gene_tier"}

var _failures: Array[String] = []
var _checks := 0


func _ready() -> void:
	print("=== t_axie_to_die: start ===")
	var ref := _load_reference()
	if ref.is_empty():
		print("t_axie_to_die: FAIL — could not read %s" % REFERENCE_PATH)
		get_tree().quit(1)
		return

	test_every_fixture_matches_the_js_engine(ref)
	test_the_algorithm_is_pure(ref)
	test_an_unmapped_part_is_reported_not_swallowed()

	print("=== t_axie_to_die: %d checks, %d failure(s) ===" % [_checks, _failures.size()])
	if _failures.is_empty():
		print("t_axie_to_die: PASS — %d checks OK" % _checks)
		get_tree().quit(0)
		return
	for f in _failures:
		print("t_axie_to_die: FAIL — %s" % f)
	get_tree().quit(1)


func _assert(cond: bool, msg: String) -> void:
	_checks += 1
	if not cond:
		_failures.append(msg)


func _load_reference() -> Dictionary:
	if not FileAccess.file_exists(REFERENCE_PATH):
		return {}
	var f := FileAccess.open(REFERENCE_PATH, FileAccess.READ)
	if f == null:
		return {}
	var parsed = JSON.parse_string(f.get_as_text())
	f.close()
	return parsed if typeof(parsed) == TYPE_DICTIONARY else {}


## JSON gives every number back as a float, so 3 and 3.0 must compare equal. Anything that is a
## whole number is compared as an integer; genuine fractions (coherence) compare with a tolerance
## far tighter than any balance-relevant difference.
func _same_number(a, b) -> bool:
	var fa := float(a)
	var fb := float(b)
	return absf(fa - fb) < 0.0000001


func _same(a, b) -> bool:
	if typeof(a) == TYPE_ARRAY and typeof(b) == TYPE_ARRAY:
		if (a as Array).size() != (b as Array).size():
			return false
		for i in (a as Array).size():
			if not _same(a[i], b[i]):
				return false
		return true
	if typeof(a) == TYPE_DICTIONARY and typeof(b) == TYPE_DICTIONARY:
		return _same_dict(a, b)
	var a_num := typeof(a) == TYPE_INT or typeof(a) == TYPE_FLOAT
	var b_num := typeof(b) == TYPE_INT or typeof(b) == TYPE_FLOAT
	if a_num and b_num:
		return _same_number(a, b)
	if a == null and b == null:
		return true
	if typeof(a) == TYPE_BOOL or typeof(b) == TYPE_BOOL:
		return bool(a) == bool(b)
	# str(), not String(): GDScript 4.7 has no String(bool) constructor, and with Variant
	# arguments that does not fail to compile — it fails at runtime and quietly compares unequal,
	# which is exactly how ten passing fields first reported themselves as "true != true".
	return str(a) == str(b)


func _same_dict(a: Dictionary, b: Dictionary) -> bool:
	for k in a.keys():
		if not b.has(k) or not _same(a[k], b[k]):
			return false
	return true


# ---------------------------------------------------------------------------

## THE ONE THAT MATTERS. Every face, field by field, against the real JS output.
func test_every_fixture_matches_the_js_engine(ref: Dictionary) -> void:
	var fixtures: Array = ref.get("fixtures", [])
	_assert(fixtures.size() >= 10,
		"the reference has %d fixtures; it had 10 when written, and shrinking it silently "
			% fixtures.size() + "narrows what this gate covers")

	for entry in fixtures:
		var fx: Dictionary = entry
		var label := String(fx.get("label", "?"))
		var expected: Dictionary = fx.get("expected", {})
		var got: Dictionary = AxieToDie.build(fx.get("axie", {}), int(fx.get("geneTier", 0)))

		# Whole-die fields.
		for js_key in ["cls", "purity", "coh", "tier", "imported"]:
			_assert(_same(expected.get(js_key), got.get(js_key)),
				"[%s] %s: JS says %s, Godot says %s"
					% [label, js_key, expected.get(js_key), got.get(js_key)])
		for js_key in RENAMED.keys():
			var gd_key := String(RENAMED[js_key])
			_assert(_same(expected.get(js_key), got.get(gd_key)),
				"[%s] %s (Godot '%s'): JS says %s, Godot says %s"
					% [label, js_key, gd_key, expected.get(js_key), got.get(gd_key)])

		# Every face, field by field. A face is where a one-point drift would hide.
		var exp_die: Array = expected.get("die", [])
		var got_die: Array = got.get("die", [])
		_assert(got_die.size() == 6, "[%s] die has %d faces, must always be 6" % [label, got_die.size()])
		_assert(exp_die.size() == got_die.size(),
			"[%s] JS produced %d faces, Godot %d" % [label, exp_die.size(), got_die.size()])
		if exp_die.size() != got_die.size():
			continue
		for i in exp_die.size():
			var ef: Dictionary = exp_die[i]
			var gf: Dictionary = got_die[i]
			for key in ["p", "t", "v", "k", "r", "src", "name", "variant", "bucket"]:
				if not ef.has(key):
					continue
				_assert(_same(ef[key], gf.get(key)),
					"[%s] face %d field '%s': JS says %s, Godot says %s (face src=%s name=%s)"
						% [label, i, key, ef[key], gf.get(key), ef.get("src"), ef.get("name")])

		# The scarcity manifest travels to the server, so it has to match too.
		_assert(_same(expected.get("scarcity"), got.get("scarcity")),
			"[%s] scarcity manifest differs — a server replaying this run would disagree about "
				% label + "which parts it saw")


## Purity is the load-bearing property: the same input must give the same die, every time, in any
## order. Asserted by calling twice and comparing, because a stray RNG draw would show up here and
## nowhere else until a ranked score was already wrong.
func test_the_algorithm_is_pure(ref: Dictionary) -> void:
	for entry in (ref.get("fixtures", []) as Array):
		var fx: Dictionary = entry
		var a: Dictionary = AxieToDie.build(fx.get("axie", {}), int(fx.get("geneTier", 0)))
		var b: Dictionary = AxieToDie.build(fx.get("axie", {}), int(fx.get("geneTier", 0)))
		_assert(JSON.stringify(a) == JSON.stringify(b),
			"[%s] two identical calls produced different dice — something in the chain is not "
				% fx.get("label", "?") + "pure, and a server replay would disagree with the client")

	# And input order must not matter: the sort happens before the cut to six.
	var fx0: Dictionary = (ref.get("fixtures", []) as Array)[1]
	var axie: Dictionary = (fx0.get("axie", {}) as Dictionary).duplicate(true)
	var parts: Array = (axie.get("parts", []) as Array).duplicate()
	parts.reverse()
	axie["parts"] = parts
	var reversed: Dictionary = AxieToDie.build(axie, int(fx0.get("geneTier", 0)))
	var original: Dictionary = AxieToDie.build(fx0.get("axie", {}), int(fx0.get("geneTier", 0)))
	_assert(JSON.stringify(reversed.get("die")) == JSON.stringify(original.get("die")),
		"reversing the API's part order changed the die — the sort is not doing its job, and the "
		+ "same Axie would import differently depending on what order the API happened to return")


## A part the catalogue has never heard of must still produce a usable face AND say so. Sky Mavis
## ships new parts whenever it likes and the catalogue already grew 192 -> 285 once; without the
## report, the only symptom is a player quietly getting a weaker die.
func test_an_unmapped_part_is_reported_not_swallowed() -> void:
	var axie := {
		"id": "9999", "class": "Plant",
		"parts": [
			{"id": "q", "name": "Nonexistent Widget", "class": "Plant", "type": "Mouth"},
			{"id": "q", "name": "Nonexistent Gizmo", "class": "Plant", "type": "Horn"},
		],
	}
	var die: Dictionary = AxieToDie.build(axie)
	var unmapped: Array = die.get("unmapped_parts", [])
	_assert(unmapped.size() == 2,
		"two unknown parts produced %d entries in unmapped_parts — the only operational signal "
			% unmapped.size() + "that the catalogue has drifted behind the live API")
	_assert(String((unmapped[0] as Dictionary).get("name", "")) == "Nonexistent Widget",
		"the report does not name the part it could not map: %s" % str(unmapped))

	# The face is still usable, and still carries the real part name for the player.
	var f0: Dictionary = (die.get("die", []) as Array)[0]
	_assert(String(f0.get("src", "")).begins_with("fallback"),
		"an unmapped part produced a '%s' face instead of a fallback" % f0.get("src", ""))
	_assert(String(f0.get("name", "")) == "Nonexistent Widget",
		"the fallback face lost the part's real name, which is what keeps it readable as an Axie "
		+ "part rather than 'Unknown'")
	# A fallback is always bucket C — a brand-new, unbalanced part must never be the best in game.
	if String(f0.get("src", "")) == "fallback":
		_assert(String(f0.get("bucket", "")) == "C",
			"a fallback face landed in bucket '%s'; it must always be C, so an unbalanced new "
				% f0.get("bucket", "") + "part can never be the strongest thing in the game")
