extends Node
## Gate for the part_faces catalogue — the table that turns a real Axie's six parts into a die.
##
## WHY A GATE AND NOT JUST A FILE
## ------------------------------
## `godot/assets/data/part_faces.json` is a COPY. The original lives at
## `assets/data/part_faces.json` in the repo root and is generated by `tools/gen_faces.mjs`,
## which still runs on the JS side and remains the only thing allowed to write it. A copy with
## no check is a copy that silently ages: the generator is re-run for a balance pass, the live
## game changes, and the Godot build keeps handing players dice built from last month's rules —
## with no error, because a stale table is still a valid table.
##
## So the first test here reads BOTH files and compares them. It is the whole point of the file.
##
## Run: godot --headless --path godot res://tests/t_part_faces.tscn

## Counts measured from the source on 2026-09-19. Written out rather than derived, so a
## regeneration that changes the shape has to be looked at by a person.
const EXPECTED_SIGNATURE := 81
const EXPECTED_VARIANT := 204
const EXPECTED_SCARCITY := 285          # = 81 + 204, every catalogued part has a bucket
const EXPECTED_BUCKETS := {"C": 174, "O": 75, "P": 18, "X": 18}

var _failures: Array[String] = []
var _checks := 0


func _ready() -> void:
	print("=== t_part_faces: start ===")
	test_the_godot_copy_matches_the_generated_source()
	test_the_catalogue_has_the_shape_the_vault_expects()
	test_every_catalogued_part_has_a_scarcity_bucket()
	test_coherence_keys_are_integers_after_loading()

	print("=== t_part_faces: %d checks, %d failure(s) ===" % [_checks, _failures.size()])
	if _failures.is_empty():
		print("t_part_faces: PASS — %d checks OK" % _checks)
		get_tree().quit(0)
		return
	for f in _failures:
		print("t_part_faces: FAIL — %s" % f)
	get_tree().quit(1)


func _assert(cond: bool, msg: String) -> void:
	_checks += 1
	if not cond:
		_failures.append(msg)


## The repo-root original, reached relative to the Godot project rather than by absolute path,
## so this works on any checkout.
func _source_path() -> String:
	return ProjectSettings.globalize_path("res://").path_join("../assets/data/part_faces.json")


func _read_json(path: String):
	if not FileAccess.file_exists(path):
		return null
	var f := FileAccess.open(path, FileAccess.READ)
	if f == null:
		return null
	var text := f.get_as_text()
	f.close()
	return JSON.parse_string(text)


# ---------------------------------------------------------------------------

## THE ONE THAT MATTERS. Compares the copy Godot ships against the file the generator writes.
func test_the_godot_copy_matches_the_generated_source() -> void:
	var source = _read_json(_source_path())
	_assert(source != null,
		"could not read the generated source at %s — if the repo layout moved, fix this test "
			% _source_path() + "rather than deleting it; an unchecked copy is the failure mode")
	if source == null:
		return
	var copy = _read_json(ContentDB.PART_FACES_PATH)
	_assert(copy != null, "could not read the Godot copy at %s" % ContentDB.PART_FACES_PATH)
	if copy == null:
		return

	# Compared section by section so a failure names what drifted, not "the files differ".
	for section in ["schema", "engineVersion", "profile"]:
		_assert(str(source.get(section)) == str(copy.get(section)),
			"'%s' differs: source has %s, the Godot copy has %s — re-copy "
				% [section, source.get(section), copy.get(section)]
			+ "assets/data/part_faces.json into godot/assets/data/")
	for section in ["constants", "familyVariant", "signatureFace", "partVariant", "scarcityBucket", "manifest"]:
		var a: Dictionary = source.get(section, {})
		var b: Dictionary = copy.get(section, {})
		_assert(a.size() == b.size(),
			"'%s' has %d entries in the generated source and %d in the Godot copy — the copy "
				% [section, a.size(), b.size()] + "is stale")
		if a.size() != b.size():
			continue
		var mismatched := 0
		var first := ""
		for k in a.keys():
			if not b.has(k) or JSON.stringify(b[k]) != JSON.stringify(a[k]):
				mismatched += 1
				if first == "":
					first = String(k)
		_assert(mismatched == 0,
			"'%s': %d entries differ between the generated source and the Godot copy "
				% [section, mismatched] + "(first: '%s')" % first)


func test_the_catalogue_has_the_shape_the_vault_expects() -> void:
	var pf: Dictionary = ContentDB.part_faces
	_assert(not pf.is_empty(),
		"ContentDB.part_faces is empty — Vault/Import would build every imported Axie as a "
		+ "blank die, which looks like bad luck rather than a missing file")
	if pf.is_empty():
		return
	_assert((pf.get("signatureFace", {}) as Dictionary).size() == EXPECTED_SIGNATURE,
		"signatureFace has %d entries, expected %d"
			% [(pf.get("signatureFace", {}) as Dictionary).size(), EXPECTED_SIGNATURE])
	_assert((pf.get("partVariant", {}) as Dictionary).size() == EXPECTED_VARIANT,
		"partVariant has %d entries, expected %d"
			% [(pf.get("partVariant", {}) as Dictionary).size(), EXPECTED_VARIANT])
	_assert((pf.get("familyVariant", {}) as Dictionary).size() == 6,
		"familyVariant should cover all 6 classes, has %d"
			% (pf.get("familyVariant", {}) as Dictionary).size())

	# Every signature face must be usable as a die face: the die builder reads p/t/v/k/r.
	var bad := 0
	var example := ""
	for key in (pf.get("signatureFace", {}) as Dictionary).keys():
		var face: Dictionary = pf["signatureFace"][key]
		if not (face.has("p") and face.has("t") and face.has("v") and face.has("k") and face.has("r")):
			bad += 1
			if example == "":
				example = String(key)
	_assert(bad == 0,
		"%d signature faces are missing one of p/t/v/k/r (first: '%s') — an incomplete face "
			% [bad, example] + "would import as a partly-blank die")


## 285 = 81 + 204. Every part the catalogue describes must also have a scarcity bucket, because
## the bucket drives the coherence floor; a part with a face but no bucket would be scored as if
## it were the most common thing in the game.
func test_every_catalogued_part_has_a_scarcity_bucket() -> void:
	var pf: Dictionary = ContentDB.part_faces
	if pf.is_empty():
		return
	var scarcity: Dictionary = pf.get("scarcityBucket", {})
	_assert(scarcity.size() == EXPECTED_SCARCITY,
		"scarcityBucket has %d entries, expected %d (= %d signature + %d variant)"
			% [scarcity.size(), EXPECTED_SCARCITY, EXPECTED_SIGNATURE, EXPECTED_VARIANT])

	var missing := 0
	var example := ""
	for section in ["signatureFace", "partVariant"]:
		for key in (pf.get(section, {}) as Dictionary).keys():
			if not scarcity.has(key):
				missing += 1
				if example == "":
					example = String(key)
	_assert(missing == 0,
		"%d catalogued parts have no scarcity bucket (first: '%s')" % [missing, example])

	var counts: Dictionary = {}
	for k in scarcity.keys():
		var b := String(scarcity[k])
		counts[b] = int(counts.get(b, 0)) + 1
	for bucket in EXPECTED_BUCKETS.keys():
		_assert(int(counts.get(bucket, -1)) == int(EXPECTED_BUCKETS[bucket]),
			"bucket '%s' holds %s parts, expected %d — the catalogue was regenerated with a "
				% [bucket, counts.get(bucket, "none"), int(EXPECTED_BUCKETS[bucket])]
			+ "different scarcity split and that is a balance change, not a copy")


## JSON has no integer keys. COH is looked up by a coherence COUNT, so it has to come back as
## one. This project already shipped a silent bug of exactly this shape in `Unit.growth`, where
## a string-keyed reader never saw integer-keyed writes and five relics were inert.
func test_coherence_keys_are_integers_after_loading() -> void:
	var pf: Dictionary = ContentDB.part_faces
	if pf.is_empty():
		return
	var consts: Dictionary = pf.get("constants", {})
	_assert(consts.has("COH"), "constants has no COH table")
	if not consts.has("COH"):
		return
	var coh: Dictionary = consts["COH"]
	for n in range(0, 7):
		_assert(coh.has(n),
			"COH has no entry for coherence %d — the keys came back as %s, so every lookup by "
				% [n, str(coh.keys())] + "number misses and every imported Axie scores as if it "
			+ "had the worst possible coherence")
		if coh.has(n):
			_assert(typeof(coh[n]) == TYPE_FLOAT and float(coh[n]) > 0.0,
				"COH[%d] is %s, expected a positive number" % [n, coh[n]])
	# And the floor really is a floor: coherence should not get worse as parts match.
	for n in range(1, 7):
		if coh.has(n) and coh.has(n - 1):
			_assert(float(coh[n]) >= float(coh[n - 1]),
				"COH[%d] (%f) is below COH[%d] (%f) — matching more parts made the Axie worse"
					% [n, float(coh[n]), n - 1, float(coh[n - 1])])
