class_name AxieToDie
extends Object
## Turns a real Axie NFT's six parts into a six-face die. Port of src/engine.js `axieToDie()`
## (:275) and its helper chain: partKey, sgTier/sgTierEff, diePurity, coherenceMod, partBudget,
## affValue, resolveFace, fallbackFace, scarcityManifest.
##
## PURE. No RNG, no Time, no I/O, no network — the same invariant the JS carries (engine.js:118,
## "AC-1, BLOCKING"). The reason is not tidiness: `api/submit-run.js` replays a ranked run on the
## server and has to rebuild the SAME die from the same part data. One random draw in here would
## make a score wrong silently, without throwing.
##
## All tuning lives in `ContentDB.part_faces` (generated by tools/gen_faces.mjs). Nothing in this
## file hardcodes a face value; if a number appears below it is a structural constant of the
## algorithm, not balance.

const SLOT_ORDER := ["mouth", "horn", "back", "tail", "eyes", "ears"]
const ORIGIN_CLASS_MAP := {"dawn": "beast", "dusk": "reptile", "mech": "bug"}
const CLASSES := ["plant", "beast", "aqua", "reptile", "bug", "bird"]

## src/data.js:9 — the blank face.
static func blank_face() -> Dictionary:
	return {"p": "blank", "t": "blank", "v": 0, "k": [], "r": 0}


static func _pf() -> Dictionary:
	return ContentDB.part_faces


static func _consts() -> Dictionary:
	return (ContentDB.part_faces.get("constants", {}) as Dictionary)


# ---------------------------------------------------------------------------
# Normalisation — the lookup key. Every table in part_faces is keyed by it, so a byte of
# difference here misses every row and silently drops the die to fallbacks.
# ---------------------------------------------------------------------------

## Keeps dawn/dusk/mech as themselves — unlike map_axie_class(), which collapses them. The
## catalogue has 18 secret-class parts with their own faces, so the key needs the real class.
static func norm_part_class(x) -> String:
	var c := String(x if x != null else "").strip_edges().to_lower()
	return "aqua" if c == "aquatic" else c


static func norm_slot(x) -> String:
	return String(x if x != null else "").strip_edges().to_lower()


## Strips the stage suffix (" α", "α", " +", "+"), trims, collapses double spaces.
## "Nut Cracker α" -> "Nut Cracker". Must match gen_faces.mjs's baseName() BYTE FOR BYTE.
static func base_name(x) -> String:
	var t := String(x if x != null else "")
	while true:
		var u := t
		# JS: /[\s]*[α+]\s*$/ — trailing whitespace, then one α or +, then trailing whitespace.
		var stripped := u.strip_edges(false, true)
		if stripped.ends_with("α") or stripped.ends_with("+"):
			u = stripped.substr(0, stripped.length() - 1).strip_edges(false, true)
		if u == t:
			break
		t = u
	t = t.strip_edges()
	while t.find("  ") != -1:
		t = t.replace("  ", " ")
	return t


static func part_key(part: Dictionary) -> String:
	return "%s|%s|%s" % [norm_part_class(part.get("class")), norm_slot(part.get("type")),
		base_name(part.get("name"))]


## The die's class. Collapses dawn/dusk/mech; an unrecognised class becomes beast rather than
## crashing (JS: "an toàn thay vì crash").
static func map_axie_class(axie_class_name) -> String:
	var c := String(axie_class_name if axie_class_name != null else "").to_lower()
	if CLASSES.has(c):
		return c
	if c == "aquatic":
		return "aqua"
	if ORIGIN_CLASS_MAP.has(c):
		return String(ORIGIN_CLASS_MAP[c])
	return "beast"


# ---------------------------------------------------------------------------
# Special genes
# ---------------------------------------------------------------------------

## §3.4a / E16-bis — the 8-step specialGenes ladder. The alias table is DATA
## (part_faces.constants.SG_TIER), never hardcoded. Anything unrecognised is tier 0, which is the
## safe default and is what killed v1's 30% inflation bug (`if (part.specialGenes != null)` was
## true for very nearly every part).
static func sg_tier(part: Dictionary) -> int:
	var raw = part.get("specialGenes")
	if raw == null:
		return 0
	var list: Array = raw if raw is Array else [raw]
	var tbl: Dictionary = _consts().get("SG_TIER", {})
	var best := 0
	for x in list:
		var k := ""
		if typeof(x) == TYPE_INT or typeof(x) == TYPE_FLOAT:
			if not (float(x) > 0.0):
				continue
			k = str(int(x))
		else:
			k = String(x).strip_edges().to_lower()
			# JS: .replace(/[\s_-]+/g,'')
			for ch in [" ", "\t", "\n", "_", "-"]:
				k = k.replace(ch, "")
		if k == "" or k == "none" or k == "null" or k == "false":
			continue
		if _is_all_zeroes(k):     # '000000' and any all-zero bitmask means NO gene
			continue
		if not tbl.has(k):        # unknown -> tier 0
			continue
		var t := int(tbl[k])
		if t > best:
			best = t
	return best


static func _is_all_zeroes(k: String) -> bool:
	if k == "":
		return false
	for i in k.length():
		if k[i] != "0":
			return false
	return true


## §3.4a-3 — the `origin` gene and the O/P buckets measure the SAME fact ("this part is from the
## Origin line"). Counting both is charging twice, so the deterministic axis (the bucket, read
## from the catalogue) wins and the gene is neutralised. On a C-bucket part the tier still
## applies — which means the catalogue has fallen behind.
static func sg_tier_eff(part: Dictionary, bucket: String) -> int:
	var t := sg_tier(part)
	var org = _consts().get("SG_TIER", {}).get("origin")
	if org != null and t == int(org) and (bucket == "O" or bucket == "P"):
		return 0
	return t


static func gene_mult(t: int) -> float:
	return 1.0 + float(_consts().get("SG_STEP", 0)) * float(t)


static func r_bonus(t: int) -> int:
	var arr: Array = _consts().get("SG_RBONUS", [0])
	return int(arr[t]) if t >= 0 and t < arr.size() else 0


# ---------------------------------------------------------------------------
# Coherence — a property of the WHOLE die, not of any one part (§3.4b)
# ---------------------------------------------------------------------------

## Computed against map_axie_class(), not the raw part class: that is what makes a Dawn part on a
## Dawn Axie COUNT AS MATCHING with no special case. A die missing parts keeps the RATIO, so it is
## not punished twice — once for the useless BLANK face and again for coherence.
static func die_purity(parts: Array, body_cls: String) -> int:
	var n := parts.size()
	if n == 0:
		return 6
	var match_count := 0
	for p in parts:
		if map_axie_class((p as Dictionary).get("class")) == body_cls:
			match_count += 1
	return match_count if n == 6 else int(round(6.0 * float(match_count) / float(n)))


static func coherence_mod(parts: Array, body_cls: String) -> float:
	var coh_tbl: Dictionary = _consts().get("COH", {})
	var pur := clampi(die_purity(parts, body_cls), 0, 6)
	var m := float(coh_tbl.get(pur, 1.0))
	var scarcity: Dictionary = _pf().get("scarcityBucket", {})
	for p in parts:
		if String(scarcity.get(part_key(p), "")) == "X":
			m = maxf(m, float(_consts().get("COH_FLOOR_SECRET", m)))
			break
	return m


## §3.4a-2 + §3.4c — one part's budget on this die.
## B_acq is the MONEY ceiling (bucket x gene, capped at B_CAP0); B_run is the PLAY ceiling
## (+GENE_STEP per geneTier, capped at B_CAP_RUN); B_final multiplies by coherence.
static func part_budget(bucket: String, part: Dictionary, gene_tier: int, coh: float) -> float:
	var c := _consts()
	var s: Dictionary = c.get("S", {})
	var acq := minf(float(c.get("B_C", 0)) * float(s.get(bucket, 1.0))
		* gene_mult(sg_tier_eff(part, bucket)), float(c.get("B_CAP0", 1e9)))
	var run := minf(acq + float(c.get("GENE_STEP", 0)) * float(gene_tier), float(c.get("B_CAP_RUN", 1e9)))
	return run * coh


## F5b is AFFINE in the budget on both branches, so the generator ships exactly two coefficients
## (m, c) instead of making this file copy the whole keyword price table — a second copy would
## certainly drift. `lift` carries the F6 monotone bump and REPAIR, which are per-BUCKET decisions
## the affine model does not know about.
static func aff_value(model: Dictionary, budget: float, lift) -> int:
	var x := float(model.get("m", 0)) * budget - float(model.get("c", 0))
	var base := int(floor(x)) if String(model.get("mode", "")) == "f" else int(round(x))
	return maxi(1, base) + (int(lift) if lift != null else 0)


# ---------------------------------------------------------------------------
# Face resolution
# ---------------------------------------------------------------------------

## §5 E1 — a part that EXISTS in the real API but NOT in the catalogue. This is the highest-
## probability edge case, not a hypothetical: the catalogue already grew 192 -> 285 once, and Sky
## Mavis ships new parts whenever it likes. Without this branch, importing an Axie with a new part
## produces a DEAD face — exactly the silent failure this whole system exists to prevent.
##
## Four decisions, each load-bearing:
##  - variant 'A' (the baseline of all 36 families), never random, so this stays PURE and replayable
##  - bucket 'C' always, so an unbalanced new part can never be the strongest thing in the game
##  - still shows the part's REAL NAME, keeping the fantasy instead of saying "Unknown Part"
##  - `unmapped_parts` collects what was missed, the only operational signal that the catalogue has
##    drifted. Collected as data rather than logged from inside the algorithm, so the face value
##    never depends on a side channel.
static func fallback_face(part: Dictionary, coh: float, gene_tier: int,
		unmapped: Array = []) -> Dictionary:
	var cls := norm_part_class(part.get("class"))
	var slot := norm_slot(part.get("type"))
	var nm := base_name(part.get("name"))
	unmapped.append({"cls": cls, "slot": slot, "name": nm})

	var fam: Dictionary = _pf().get("familyVariant", {}).get(cls, {})
	var slot_tbl: Dictionary = fam.get(slot, {})
	var tpl = slot_tbl.get("A")
	if tpl == null:
		# E3 — slot or class unrecognised. This is the ONLY case that yields a blank face.
		var f := blank_face()
		f["src"] = "fallback-blank"
		f["name"] = nm
		return f

	var t: Dictionary = tpl
	var lift = (t.get("lift", {}) as Dictionary).get("C")
	var n := aff_value(t, part_budget("C", part, gene_tier, coh), lift)
	var is_v0 := String(t.get("t", "")) == "buff" or String(t.get("t", "")) == "debuff"
	return {
		"p": slot, "t": t.get("t"), "v": 0 if is_v0 else n,
		"k": _bind_keywords(t.get("k", []), n),
		"r": int((_consts().get("SCARCITY_RFLOOR", {}) as Dictionary).get("C", 0)),
		"src": "fallback", "name": nm, "variant": "A", "bucket": "C",
	}


## Keywords ending in `:N` carry the computed number. On a v=0 face that number is the MAGNITUDE
## of the keyword, not the face value — which is why it is bound here and not read off `v`.
static func _bind_keywords(keys, n: int) -> Array:
	var out: Array = []
	for x in (keys as Array):
		var s := String(x)
		if s.ends_with(":N"):
			out.append(s.substr(0, s.length() - 1) + str(n))
		else:
			out.append(s)
	return out


## §3.6 steps 1-2. `suppress` is §3.4b: at purity <= 2 the sharp keyword is REPLACED by a blunt
## one and the budget difference is refunded into v. A signature face is never suppressed and
## never takes the bucket multiplier (§3.3).
static func resolve_face(part: Dictionary, coh: float, suppress: bool, gene_tier: int,
		unmapped: Array = []) -> Dictionary:
	var pf := _pf()
	var k := part_key(part)
	var sig = (pf.get("signatureFace", {}) as Dictionary).get(k)
	var bucket := String((pf.get("scarcityBucket", {}) as Dictionary).get(k, "C"))

	if sig != null:
		var sg: Dictionary = sig
		var sig_v0 := String(sg.get("t", "")) == "buff" or String(sg.get("t", "")) == "debuff"
		return {
			"p": sg.get("p"), "t": sg.get("t"),
			"v": 0 if sig_v0 else maxi(1, int(round(float(sg.get("v", 0)) * coh))),
			"k": (sg.get("k", []) as Array).duplicate(),
			"r": mini(4, int(sg.get("r", 0)) + r_bonus(sg_tier_eff(part, bucket))),
			"src": "sig", "name": base_name(part.get("name")),
		}

	var letter = (pf.get("partVariant", {}) as Dictionary).get(k)
	if letter == null:
		return fallback_face(part, coh, gene_tier, unmapped)
	var fam: Dictionary = (pf.get("familyVariant", {}) as Dictionary).get(
		norm_part_class(part.get("class")), {})
	var slot_tbl: Dictionary = fam.get(norm_slot(part.get("type")), {})
	var tpl = slot_tbl.get(String(letter))
	if tpl == null:
		return fallback_face(part, coh, gene_tier, unmapped)

	var t: Dictionary = tpl
	var model: Dictionary = t.get("sup", t) if (suppress and t.has("sup")) else t
	var lift = (t.get("lift", {}) as Dictionary).get(bucket)
	var n := aff_value(model, part_budget(bucket, part, gene_tier, coh), lift)
	var is_v0 := String(t.get("t", "")) == "buff" or String(t.get("t", "")) == "debuff"
	var r_floor := int((_consts().get("SCARCITY_RFLOOR", {}) as Dictionary).get(bucket, 0))
	return {
		"p": norm_slot(part.get("type")), "t": t.get("t"), "v": 0 if is_v0 else n,
		"k": _bind_keywords(model.get("k", []), n),
		# F8: a variant face is clamped to r <= 3 — only a signature can reach COSMIC.
		"r": mini(3, r_floor + r_bonus(sg_tier_eff(part, bucket))),
		"src": "var", "name": base_name(part.get("name")),
		"variant": String(letter), "bucket": bucket,
	}


## §3.9 — the scarcity manifest travels with the die so a server can re-verify it without
## calling the Axie API again.
static func scarcity_manifest(parts: Array) -> Array:
	var out: Array = []
	var scarcity: Dictionary = _pf().get("scarcityBucket", {})
	for p in parts:
		var k := part_key(p)
		out.append({"k": k, "b": String(scarcity.get(k, "?")), "g": sg_tier(p)})
	return out


# ---------------------------------------------------------------------------
# The entry point
# ---------------------------------------------------------------------------

## `axie_data` is the shape `api/axie.js` returns: {id, class, image, parts:[{id,name,class,type,
## specialGenes}]}. Returns a hero-record-shaped Dictionary the roster can carry.
static func build(axie_data: Dictionary, gene_tier: int = 0) -> Dictionary:
	var raw: Array = axie_data.get("parts", [])
	var body_cls := map_axie_class(axie_data.get("class"))

	# §3.10 — the TRUE body class is dawn/dusk/mech before ORIGIN_CLASS_MAP collapses it to
	# beast/reptile/bug. Kept separately so the UI can show the real identity ("a real Dawn Axie")
	# instead of repeating the mapped class. The mapping still decides passive/colour/base HP;
	# only the display needs this.
	var raw_body_cls := String(axie_data.get("class", "")).strip_edges().to_lower()
	var secret_cls = raw_body_cls if ORIGIN_CLASS_MAP.has(raw_body_cls) else null

	# N3/E2 — sort BEFORE cutting to 6, or the die depends on whatever order the API returned.
	# Stable by (SLOT_ORDER, partKey) so two parts in the same slot are ordered too (E5).
	var parts: Array = raw.duplicate()
	parts.sort_custom(func(a, b):
		var da := SLOT_ORDER.find(norm_slot((a as Dictionary).get("type")))
		var db := SLOT_ORDER.find(norm_slot((b as Dictionary).get("type")))
		if da != db:
			return da < db
		return part_key(a) < part_key(b))
	if parts.size() > 6:
		parts = parts.slice(0, 6)

	var has_tables := not _pf().is_empty()
	var coh := coherence_mod(parts, body_cls) if has_tables else 1.0
	var secret := false
	if has_tables:
		var scarcity: Dictionary = _pf().get("scarcityBucket", {})
		for p in parts:
			if String(scarcity.get(part_key(p), "")) == "X":
				secret = true
				break
	var suppress := has_tables and not secret and die_purity(parts, body_cls) <= 2

	var unmapped: Array = []
	var die: Array = []
	for p in parts:
		# Without the catalogue the die comes out blank rather than crashing — the same choice
		# the JS makes when part_faces.js is missing from the bundle.
		die.append(resolve_face(p, coh, suppress, gene_tier, unmapped) if has_tables else blank_face())
	while die.size() < 6:
		die.append(blank_face())

	var base_hp := int((ContentDB.heroes.get(body_cls + "1", {}) as Dictionary).get("max_hp", 14))
	var hp_steps: Array = _consts().get("HP_STEP", [0])
	var idx := clampi(gene_tier, 0, 6)
	var hp_step := int(hp_steps[idx]) if idx < hp_steps.size() else 0
	var hp := maxi(1, int(round(float(base_hp) * coh)) + hp_step)

	return {
		"n": "Axie #%s" % str(axie_data.get("id", "")),
		"cls": body_cls, "secret_cls": secret_cls, "tier": 1, "max_hp": hp,
		"die": die, "imported": true,
		"axie_id": axie_data.get("id"),
		"genes": axie_data.get("genes"),   # what the 3D preview is rebuilt from
		"purity": die_purity(parts, body_cls), "coh": coh, "gene_tier": gene_tier,
		"scarcity": scarcity_manifest(parts),
		# Operational signal, carried as data: non-empty means the catalogue has drifted behind
		# the live API and somebody should re-run tools/gen_faces.mjs.
		"unmapped_parts": unmapped,
	}
