/* gen_faces.mjs — PART SKILL IDENTITY face generator (design/gdd/part-skill-identity.md §6f)
 *
 * Turns the hand-authored design tables (§3.3a, §3.3b, §3.10, §3.11, §3.12) plus the real
 * Axie catalog into runtime face data, and adjudicates the derived numbers the doc can no
 * longer own (§6f "Derived data — GENERATOR, không ai sửa tay").
 *
 * Purity: the whole derivation path (parse -> compute -> count) is a pure function of the
 * input strings. No Math.random, no Date, no I/O below loadInputs(). --prove-determinism
 * re-runs it N times and byte-compares, because ranked runs are replay-verified server-side.
 *
 * Run:  node tools/gen_faces.mjs
 *       node tools/gen_faces.mjs --profile=reference --no-r7      (AC-9c-base baseline)
 *       node tools/gen_faces.mjs --check
 *       node tools/gen_faces.mjs --check-citations
 *       node tools/gen_faces.mjs --refresh-catalog
 */
import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import vm from 'node:vm';

const ROOT = path.resolve(new URL('.', import.meta.url).pathname, '..');
const P = (...a) => path.join(ROOT, ...a);

const IN_CATALOG = P('docs/axiedice-source/economy/parts_full_source.json');
const IN_DESIGN = P('design/gdd/part-skill-identity.md');
const IN_TUNING = P('assets/data/part_faces_tuning.json');
const OUT_MAIN = P('assets/data/part_faces.json');
const OUT_REF = P('assets/data/part_faces.ref.json');
const OUT_JS = P('src/part_faces.js');
const KNOWN_FAILURES = P('tools/known-failures.json');

const SLOT_ORDER = ['mouth', 'horn', 'back', 'tail', 'eyes', 'ears'];
const CLASS_ORDER = ['aqua', 'beast', 'bird', 'bug', 'plant', 'reptile'];
const SECRET_CLASSES = ['dawn', 'dusk', 'mech'];
const BUCKETS = ['C', 'O', 'P'];

/* ------------------------------------------------------------------ *
 * 0. Failure accumulator — every invariant is a HARD FAIL (exit != 0) *
 * ------------------------------------------------------------------ */
const failures = [];
const findings = [];
function hardFail(id, row, expected, actual, extra) {
  failures.push({ id, row, expected, actual, extra });
}
function finding(kind, msg, data) { findings.push({ kind, msg, data }); }

/* --------------------------------------------- *
 * 1. Defaults for §7 tuning knobs (bootstrapped) *
 * --------------------------------------------- */
const DEFAULT_TUNING = {
  _comment: 'Tuning knobs for §7 of design/gdd/part-skill-identity.md. Generated by tools/gen_faces.mjs on first run; edit by hand thereafter. Values are at the REFERENCE scale (B_REF=6.00) unless noted — see F4.',
  B_REF: 6.0,
  B_C: { production: 2.8, reference: 6.0 },
  S: { C: 1.0, O: 1.267, P: 1.6, X: 1.467 },
  SlotMod: { mouth: 1.0, horn: 1.1, back: 1.05, tail: 0.95, eyes: 1.0, ears: 1.0 },
  R: { dmg: 1.0, heal: 1.0, shield: 0.86, poison: 1.55, mana: 2.25, buff: 2.6, debuff: 2.6, summon: 4.2 },
  AOE_KWB: 0.55,
  GENE_STEP: 0.53,
  GENE_MAX: 6,
  SG_STEP: 0.071,
  B_CAP_RUN: 7.2,
  TTK_CEIL_T3: 1.15,
  HERO_T3_AVG_FACE: 6.39,
  SPREAD_OWN_MAX: 2.4,
  SBC_CAP: 14,
  HANDICAP_K: 2.0,
  SPARE_MAX: 12,
  REPAIR_MAX_BUMP: 2,
  REPAIR_MAX_COLLISIONS: 8,
  SPREAD_MAX_BUMP: 2,
  SIG_LIFT_MAX: 3,
  KW_SUPPRESS_THRESHOLD: 2.0,
  SIG_BUDGET: { 0: 6.0, 1: 8.5, 2: 12.0, 3: 17.0 },
  SCARCITY_RFLOOR: { C: 0, O: 1, P: 2, X: 2 },
  COH: { 6: 1.0, 5: 0.97, 4: 0.94, 3: 0.91, 2: 0.88, 1: 0.85, 0: 0.82 },
  COH_FLOOR_SECRET: 0.91,
  KW_FLAT: {
    heavy: -0.4, decay: -0.8, vital: 1.0, rerollup: 1.4, cantrip: 1.5, lifesteal: 1.5,
    growth: 1.5, exec: 2.0, pierce: 2.3, freeze: 2.6, undying: 2.8, cleave: 3.1,
    stun: 3.4, aoe: 3.6,
  },
  KW_PER_STACK: {
    selfharm: -0.25, crit: 0.045, regen: 0.5, weaken: 0.6, poison: 0.7, thorns: 0.7,
    vulnerable: 0.75, blind: 0.9, burn: 0.55, mana: 1.1,
  },
  KW_PER_EXTRA: { chain: 1.4, multi: 1.6 },
  KW_UNPRICED: ['echo', 'plague', 'bastion', 'overflow'],
  TYPE_COST: { aqua: { mana: 1.2 }, plant: { shield: 1.7 }, bug: { poison: 0.9 } },
  CLS_SURCHARGE: {
    beast: { exec: 0.8 },
    bird: { pierce: 0.9, aoe: 1.4 },
    aqua: { mana: 0.45 },
    bug: { poison: 0.5 },
    reptile: { thorns: 0.6 },
  },
  CLS_SURCHARGE_PER_STACK: { aqua: ['mana'] },
};

/* keyword whitelist — §3.7 "ĐÃ IMPLEMENT" column. shieldself deliberately absent (I10). */
const KW_WHITELIST = new Set([
  'cleave', 'pierce', 'aoe', 'cantrip', 'heavy', 'growth', 'decay', 'vital', 'lifesteal',
  'exec', 'multi', 'chain', 'selfharm', 'mana', 'rerollup', 'crit', 'burn', 'poison',
  'weaken', 'vulnerable', 'blind', 'thorns', 'regen', 'stun', 'freeze', 'undying',
  'enrage', 'echo', 'plague', 'bastion', 'overflow', 'selfkill',
]);
/* §3.7a kwPure = everything NOT in this exclusion list (src/engine.js :487-489). */
const KW_NOT_PURE = new Set([
  'aoe', 'cantrip', 'heavy', 'echo', 'selfkill', 'plague', 'bastion', 'overflow',
  'multi', 'chain', 'selfharm', 'crit', 'cleave', 'pierce', 'lifesteal', 'growth',
  'decay', 'vital', 'rerollup', 'exec',
]);
const KWPURE_FOE = new Set(['burn', 'poison', 'weaken', 'vulnerable', 'blind', 'stun', 'freeze']);
const KWPURE_ALLY = new Set(['thorns', 'regen', 'undying', 'enrage']);
/* §3.13b risk 2 / I21 — class identity whitelist */
const CLASS_TYPE_BAN = { beast: ['shield', 'heal'], bird: ['shield', 'heal'], plant: ['poison'] };

/* ------------------------------- *
 * 2. Small pure helpers           *
 * ------------------------------- */
const normClass = (x) => {
  const s = String(x || '').toLowerCase().trim();
  return s === 'aquatic' ? 'aqua' : s;
};
const normSlot = (x) => String(x || '').toLowerCase().trim();
/* §3.1 baseName: strip trailing α / + then trim + collapse inner double spaces */
function baseName(x) {
  let s = String(x == null ? '' : x);
  for (;;) {
    const t = s.replace(/[\s]*[α+]\s*$/u, '');
    if (t === s) break;
    s = t;
  }
  return s.trim().replace(/\s{2,}/g, ' ');
}
const partKey = (cls, slot, name) => `${normClass(cls)}|${normSlot(slot)}|${baseName(name)}`;
const kwName = (k) => String(k).split(':')[0];
const kwMag = (k) => {
  const bits = String(k).split(':');
  return bits.length > 1 ? Number(bits[1]) : null;
};
const sortedKw = (k) => k.slice().sort().join(',');
/* engine-visible tuple: (p, t, v, k) — class deliberately excluded (§0-bis basis 3) */
const engineTuple = (f) => `${f.p}|${f.t}|${f.v}|${sortedKw(f.k)}`;
/* R5/R8 family/slot tuple: (t, v, sortedKeys) */
const repairTuple = (f) => `${f.t}|${f.v}|${sortedKw(f.k)}`;
/* R7 keyword-set tuple: (t, sortedKeys) */
const kwSetTuple = (f) => `${f.t}|${sortedKw(f.k)}`;

/* ------------------------------- *
 * 3. CLI                          *
 * ------------------------------- */
function parseArgs(argv) {
  const o = {
    profile: 'production', check: false, checkCitations: false, refreshCatalog: false,
    noR7: false, noRepair: false, write: true, proveDeterminism: 8, json: false, quiet: false,
  };
  for (const a of argv) {
    if (a.startsWith('--profile=')) o.profile = a.slice(10);
    else if (a === '--check') { o.check = true; o.write = false; }
    else if (a === '--check-citations') { o.checkCitations = true; o.write = false; }
    else if (a === '--refresh-catalog') o.refreshCatalog = true;
    else if (a === '--no-r7') o.noR7 = true;            // AC-9c-base: skip R7/R8/SPREAD
    else if (a === '--no-repair') o.noRepair = true;
    else if (a === '--repair-all-buckets') o.repairAllBuckets = true;    // additionally skip §3.5d REPAIR
    else if (a === '--dry-run') o.write = false;
    else if (a === '--json') o.json = true;
    else if (a === '--explain') o.explain = true;
    else if (a === '--matrix') o.matrix = true;
    else if (a === '--strict') o.strict = true;
    else if (a === '--quiet') o.quiet = true;
    else if (a.startsWith('--prove-determinism=')) o.proveDeterminism = Number(a.slice(20));
    else if (a === '--help' || a === '-h') o.help = true;
    else { console.error(`gen_faces: unknown flag ${a}`); process.exit(2); }
  }
  if (o.profile !== 'production' && o.profile !== 'reference') {
    console.error(`gen_faces: --profile must be production|reference, got ${o.profile}`);
    process.exit(2);
  }
  return o;
}

const HELP = `gen_faces.mjs — derive part faces from design/gdd/part-skill-identity.md §6f

  --profile=production   B[C]=2.80, writes assets/data/part_faces.json      (default)
  --profile=reference    B[C]=6.00, writes assets/data/part_faces.ref.json  (AC-7)
  --check                do not write; diff against the committed snapshot  (CI gate)
  --check-citations      verify every file.js:NNN citation in the doc       (AC-33)
  --refresh-catalog      re-import the catalog, list new/missing partKeys   (E1 runbook)
  --no-r7                skip R7/R8/SPREAD — pre-R7 baseline                (AC-9c-base)
  --no-repair            additionally skip the §3.5d REPAIR pass
  --repair-all-buckets   REPAIR unreachable (variant,bucket) instances too (literal §3.5d)
  --dry-run              compute + report, write nothing
  --json                 emit the report as JSON
  --explain              list every colliding pair (which parts lost a distinct face)
  --strict               ignore tools/known-failures.json; report the true invariant state
  --matrix               print engine-distinct + identity-distinct for every profile x flag
                         combination in one table, then exit (settles AC-9c-base)
  --prove-determinism=N  re-run the derivation N times and byte-compare (default 8)
`;

/* ================================================================= *
 * STAGE 1 — loadCatalog()                                            *
 * ================================================================= */
function loadCatalog(rows) {
  const byKey = new Map();
  for (const r of rows) {
    const cls = normClass(r.class);
    const slot = normSlot(r.slot);
    const nm = baseName(r.name);
    const k = `${cls}|${slot}|${nm}`;
    if (!byKey.has(k)) byKey.set(k, { key: k, cls, slot, name: nm, stages: new Set(), ids: [] });
    const e = byKey.get(k);
    e.stages.add(Number(r.stage));
    e.ids.push(r.id);
  }
  const identities = [];
  for (const e of byKey.values()) {
    e.bucket = bucketOf(e.cls, e.stages);
    identities.push(e);
  }
  identities.sort((a, b) => (a.key < b.key ? -1 : a.key > b.key ? 1 : 0));
  return identities;
}
/* F1 bucket() */
function bucketOf(cls, stages) {
  if (SECRET_CLASSES.includes(cls)) return 'X';
  const s0 = stages.has(0), s2 = stages.has(2);
  if (s0 && s2) return 'P';
  if (s0) return 'O';
  if (s2) return 'C';
  return 'C'; /* E8: stages={1} does not exist today; default C, never throw */
}

/* ================================================================= *
 * STAGE 2 — loadDesign(): parse §3.3a, §3.3b, §3.10, §3.11, §3.12    *
 * ================================================================= */
function sliceSection(md, startRe, endRe, label) {
  const lines = md.split('\n');
  let s = -1, e = lines.length;
  for (let i = 0; i < lines.length; i++) if (startRe.test(lines[i])) { s = i; break; }
  if (s < 0) throw new Error(`gen_faces: cannot locate section ${label} in the design doc`);
  for (let i = s + 1; i < lines.length; i++) if (endRe.test(lines[i])) { e = i; break; }
  return { lines: lines.slice(s, e), offset: s };
}
const cells = (line) => line.trim().replace(/^\|/, '').replace(/\|$/, '').split('|').map((c) => c.trim());
const isTableRow = (l) => /^\s*\|/.test(l) && !/^\s*\|[\s:|-]+\|\s*$/.test(l);
const stripFmt = (s) => String(s).replace(/`/g, '').replace(/\*\*/g, '').replace(/\*/g, '').trim();

/* Parse a face spec like "dmg 13 · aoe · cleave · burn:8" (signature) */
function parseFaceSpec(raw, where) {
  const s = stripFmt(raw);
  const parts = s.split('·').map((x) => x.trim()).filter(Boolean);
  if (!parts.length) throw new Error(`gen_faces: unparseable face spec at ${where}: "${raw}"`);
  const head = parts[0].split(/\s+/);
  const t = head[0];
  if (head.length < 2 || !/^-?\d+$/.test(head[1])) {
    throw new Error(`gen_faces: face spec at ${where} has no numeric value: "${raw}"`);
  }
  return { t, v: Number(head[1]), k: parts.slice(1) };
}
/* Parse a variant "t · k" cell like "debuff · `vulnerable:N`" */
const FACE_TYPES = ['dmg', 'heal', 'shield', 'poison', 'mana', 'buff', 'debuff', 'summon'];
function parseVariantSpec(raw, where) {
  const s = stripFmt(raw);
  const parts = s.split('·').map((x) => x.trim()).filter(Boolean);
  if (!parts.length) throw new Error(`gen_faces: unparseable variant t·k at ${where}: "${raw}"`);
  if (!FACE_TYPES.includes(parts[0])) {
    throw new Error(`gen_faces: ${where} — "${parts[0]}" is not a face type. `
      + `The 't · k' cell reads "${String(raw).trim()}"; expected one of ${FACE_TYPES.join(', ')} `
      + `followed by ' · '-separated keywords.`);
  }
  for (const k of parts.slice(1)) {
    if (!/^[a-z]+(:(N|\d+))?$/.test(k)) {
      throw new Error(`gen_faces: ${where} — "${k}" is not a keyword (expected name or name:N). Cell reads "${String(raw).trim()}".`);
    }
  }
  return { t: parts[0], k: parts.slice(1) };
}

/* §3.4b SUPPRESS_SOURCES + SUPPRESS_CANDIDATES[source][typeGroup].
   The suppressible set is an ENUMERATION, not a cost threshold (the doc says so explicitly:
   "BẢNG LIỆT KÊ là ĐỊNH NGHĨA"), and candidate priority now depends on the face's type group
   because §3.7a allows different kwPure directions per group. */
const TYPE_GROUP = { dmg: 'A', debuff: 'A', shield: 'B', heal: 'B', buff: 'B', mana: 'C', summon: 'C', poison: 'C' };
function parseSuppression(md) {
  const srcM = /SUPPRESS_SOURCES\s*=\s*\{([^}]*)\}/.exec(md);
  if (!srcM) throw new Error('gen_faces: cannot locate SUPPRESS_SOURCES in §3.4b — the suppression '
    + 'spec was renamed or moved. Re-read §3.4b and update parseSuppression().');
  const sources = srcM[1].split(',').map((x) => x.trim()).filter(Boolean);
  const blockM = /SUPPRESS_CANDIDATES\[source\]\[typeGroup\][\s\S]*?\n```/.exec(md);
  if (!blockM) throw new Error('gen_faces: cannot locate the SUPPRESS_CANDIDATES[source][typeGroup] '
    + 'block in §3.4b. Re-read §3.4b and update parseSuppression().');
  const cand = {};
  let cur = null;
  for (const line of blockM[0].split('\n')) {
    const head = /^\s{2}([a-z]+(?::\*|:\d+)?)\s+([ABC])\s*:/.exec(line);
    if (head) { cur = head[1]; cand[cur] = cand[cur] || { A: [], B: [], C: [] }; }
    if (!cur) continue;
    for (const g of line.matchAll(/\b([ABC])\s*:\s*\[([^\]]*)\]/g)) {
      cand[cur][g[1]] = g[2].split(',').map((x) => x.trim()).filter(Boolean);
    }
    for (const g of line.matchAll(/\b([ABC])\s*:\s*—/g)) cand[cur][g[1]] = [];
  }
  for (const src of sources) {
    if (!cand[src]) {
      throw new Error(`gen_faces: SUPPRESS_SOURCES lists "${src}" but SUPPRESS_CANDIDATES has no row for it (§3.4b)`);
    }
  }
  return { sources, cand };
}

function parseSignatures(md) {
  const sigs = new Map();
  const dup = (key, where) => {
    if (sigs.has(key)) hardFail('I3', key, 'unique SIGNATURE_FACE key', `duplicate at ${where}`);
  };
  /* §3.3a — 50 legacy FACE_NAMES */
  const a = sliceSection(md, /^#### 3\.3a /, /^#### 3\.3b /, '§3.3a');
  let nA = 0;
  for (let i = 0; i < a.lines.length; i++) {
    const l = a.lines[i];
    if (!isTableRow(l)) continue;
    const c = cells(l);
    if (c.length < 6 || !/^\d+$/.test(c[0])) continue;
    const [num, name, cls, slot, r, face] = c;
    const where = `§3.3a row #${num} (${name})`;
    const f = parseFaceSpec(face, where);
    const key = partKey(cls, slot, name);
    dup(key, where);
    sigs.set(key, { key, cls: normClass(cls), slot: normSlot(slot), name: baseName(name), r: Number(r), t: f.t, v: f.v, k: f.k, legacy: true, secret: false, num: Number(num), where });
    nA++;
  }
  /* §3.3b — 13 addendum */
  const b = sliceSection(md, /^#### 3\.3b /, /^### 3\.4 /, '§3.3b');
  let nB = 0;
  for (const l of b.lines) {
    if (!isTableRow(l)) continue;
    const c = cells(l);
    if (c.length < 7 || !/^\d+$/.test(c[0])) continue;
    const [num, name, cls, slot, r, face] = c;
    const where = `§3.3b row #${num} (${name})`;
    const f = parseFaceSpec(face, where);
    const key = partKey(cls, slot, name);
    dup(key, where);
    sigs.set(key, { key, cls: normClass(cls), slot: normSlot(slot), name: baseName(name), r: Number(r), t: f.t, v: f.v, k: f.k, legacy: false, secret: false, num: Number(num), where });
    nB++;
  }
  /* §3.10 — 18 secret */
  const s = sliceSection(md, /^### 3\.10 /, /^### 3\.11 /, '§3.10');
  let nS = 0;
  for (const l of s.lines) {
    if (!isTableRow(l)) continue;
    const c = cells(l);
    if (c.length < 6) continue;
    const m = /^(dawn|dusk|mech)\s*(?:→|->)\s*(\w+)$/.exec(stripFmt(c[0]));
    if (!m) continue;
    const [, cls, , ] = m;
    const slot = normSlot(c[1]);
    const name = stripFmt(c[2]);
    const where = `§3.10 ${cls}·${slot}·${name}`;
    const f = parseFaceSpec(c[3], where);
    const key = partKey(cls, slot, name);
    dup(key, where);
    sigs.set(key, { key, cls, slot, name: baseName(name), r: Number(stripFmt(c[4])), t: f.t, v: f.v, k: f.k, legacy: false, secret: true, mapTo: m[2], where });
    nS++;
  }
  return { sigs, counts: { legacy: nA, addendum: nB, secret: nS } };
}

function parseFamilyVariant(md) {
  const sec = sliceSection(md, /^### 3\.11 /, /^### 3\.12 /, '§3.11');
  const fam = {};              // fam[cls][slot][letter] = tpl
  const order = [];
  let nVar = 0, nSpare = 0;
  let cls = null;
  const CLS = /^####\s+([A-Z]+)\s+—/;
  const ROW = /^`([a-z]+)\.([a-z]+)\.([A-F])`$/;
  for (let i = 0; i < sec.lines.length; i++) {
    const l = sec.lines[i];
    const cm = CLS.exec(l.trim());
    if (cm) {
      cls = normClass(cm[1]);
      if (!CLASS_ORDER.includes(cls)) throw new Error(`gen_faces: §3.11 unknown class "${cm[1]}" (doc line ${sec.offset + i + 1})`);
      fam[cls] = fam[cls] || {};
      continue;
    }
    if (!isTableRow(l)) continue;
    const c = cells(l);
    if (c.length < 3) continue;
    const rm = ROW.exec(c[0].trim());
    if (!rm) continue;                                  // header row / legend row
    const [, rowCls, slot, letter] = rm;
    const docLine = sec.offset + i + 1;
    if (!cls) throw new Error(`gen_faces: §3.11 variant row before any class header (doc line ${docLine})`);
    if (normClass(rowCls) !== cls) {
      throw new Error(`gen_faces: §3.11 row "${c[0]}" sits under the ${cls.toUpperCase()} heading (doc line ${docLine})`);
    }
    if (!SLOT_ORDER.includes(slot)) throw new Error(`gen_faces: §3.11 unknown slot "${slot}" (doc line ${docLine})`);
    fam[cls][slot] = fam[cls][slot] || {};
    if (fam[cls][slot][letter]) throw new Error(`gen_faces: §3.11 duplicate variant ${cls}.${slot}.${letter} (doc line ${docLine})`);

    const reachCell = stripFmt(c[2]);
    const isSpareCell = /\(spare\)/i.test(c[1]);
    const reachable = reachCell === '\u2713' || reachCell.toLowerCase() === 'yes';
    if (isSpareCell !== !reachable) {
      throw new Error(`gen_faces: §3.11 ${cls}.${slot}.${letter} — "${c[1]}" and reachable "${c[2]}" disagree (doc line ${docLine})`);
    }
    const where = `§3.11 ${cls}.${slot}.${letter} (doc line ${docLine})`;
    let tpl;
    if (isSpareCell) {
      tpl = { id: `${cls}.${slot}.${letter}`, cls, slot, letter, t: null, k: [], spare: true, reachable: false, tabled: null, where };
      nSpare++;
    } else {
      let spec = null;
      try {
        spec = parseVariantSpec(c[1].replace(/\*\([^)]*\)\*\s*$/, ''), where);
      } catch (e) {
        hardFail('PARSE-3.11', `${cls}.${slot}.${letter}`, "a parseable 't · k' cell",
          String(c[1]).trim(), e.message.replace(/^gen_faces: /, ''));
      }
      tpl = spec
        ? { id: `${cls}.${slot}.${letter}`, cls, slot, letter, t: spec.t, k: spec.k, spare: false, reachable: true, tabled: null, where }
        : { id: `${cls}.${slot}.${letter}`, cls, slot, letter, t: null, k: [], spare: false, reachable: true, corrupt: true, tabled: null, where };
    }
    fam[cls][slot][letter] = tpl;
    order.push(tpl);
    nVar++;
  }
  /* V(class, slot) is now derived from the rows themselves, not from a hand-written header */
  const families = [];
  for (const cl of CLASS_ORDER) {
    for (const slot of SLOT_ORDER) {
      const f = (fam[cl] || {})[slot];
      if (!f) { hardFail('PARSE-3.11', `${cl}·${slot}`, 'family present in §3.11', 'missing'); continue; }
      const V = Object.keys(f).length;
      families.push({ cls: cl, slot, V });
      if (V < 4 || V > 6) hardFail('K15', `${cl}·${slot}`, 'V in [4, 6] (§3.5a)', String(V));
      const letters = Object.keys(f).sort();
      const expect = 'ABCDEF'.slice(0, V).split('');
      if (letters.join('') !== expect.join('')) {
        hardFail('PARSE-3.11', `${cl}·${slot}`, `contiguous letters ${expect.join('')}`, letters.join(''));
      }
    }
  }
  return { fam, families, nVar, nSpare, order };
}

function parsePartVariant(md) {
  const sec = sliceSection(md, /^### 3\.12 /, /^### 3\.13 /, '§3.12');
  const map = new Map();
  const perClass = {};
  let cls = null;
  const CLS = /^####\s+([A-Z]+)\s*\((\d+)\)\s*$/;
  const SLOT_LINE = /^-\s+\*\*(\w+)\*\*\s*—\s*(.*)$/;
  for (let i = 0; i < sec.lines.length; i++) {
    const raw = sec.lines[i];
    const cm = CLS.exec(raw.trim());
    if (cm) {
      cls = normClass(cm[1]);
      if (!CLASS_ORDER.includes(cls)) throw new Error(`gen_faces: §3.12 unknown class "${cm[1]}"`);
      perClass[cls] = { stated: Number(cm[2]), parsed: 0 };
      continue;
    }
    const sm = SLOT_LINE.exec(raw.trim());
    if (!sm) continue;
    if (!cls) throw new Error(`gen_faces: §3.12 slot line before any class header (doc line ${sec.offset + i + 1})`);
    const slot = normSlot(sm[1]);
    if (!SLOT_ORDER.includes(slot)) throw new Error(`gen_faces: §3.12 unknown slot "${sm[1]}"`);
    /* drop the trailing italic rationale note: *(R5: ...)* */
    let body = sm[2].replace(/\*\(.*?\)\*\s*$/, '').trim();
    for (const chunk of body.split('·').map((x) => x.trim()).filter(Boolean)) {
      const m = /^(.+?)\s*\((C|O|P)\)\s*(?:→|->)\s*(.+)$/.exec(stripFmt(chunk));
      if (!m) {
        throw new Error(`gen_faces: §3.12 unparseable assignment "${chunk}" in ${cls}·${slot} (doc line ${sec.offset + i + 1})`);
      }
      const name = baseName(stripFmt(m[1]));
      const statedBucket = m[2];
      const letter = stripFmt(m[3]);
      if (!/^[A-F]$/.test(letter)) {
        throw new Error(`gen_faces: §3.12 bad variant letter "${letter}" for ${cls}·${slot}·${name} (doc line ${sec.offset + i + 1})`);
      }
      const key = partKey(cls, slot, name);
      if (map.has(key)) {
        hardFail('I3', key, 'unique PART_VARIANT key', `duplicate in §3.12 (doc line ${sec.offset + i + 1})`);
      }
      map.set(key, { key, cls, slot, name, letter, statedBucket, line: sec.offset + i + 1 });
      perClass[cls].parsed++;
    }
  }
  /* stated spare list */
  const spareStated = [];
  for (const l of sec.lines) {
    if (!/^`[a-z]+\.[a-z]+\.[A-F]`/.test(l.trim())) continue;
    for (const m of l.matchAll(/`([a-z]+\.[a-z]+\.[A-F])`/g)) spareStated.push(m[1]);
  }
  return { map, perClass, spareStated };
}

/* ================================================================= *
 * STAGE 4 — computeVariants(): F2 -> F5a -> F4 -> F5b -> F6          *
 * ================================================================= */
function makeMath(T, profile) {
  const B_C = T.B_C[profile];
  const KW_SCALE = B_C / T.B_REF;
  const flatCost = (k) => {
    const n = kwName(k), mag = kwMag(k);
    if (T.KW_UNPRICED.includes(n)) return 0;
    if (Object.prototype.hasOwnProperty.call(T.KW_FLAT, n)) return T.KW_FLAT[n];
    if (Object.prototype.hasOwnProperty.call(T.KW_PER_STACK, n)) return T.KW_PER_STACK[n] * (mag == null ? 1 : mag);
    if (Object.prototype.hasOwnProperty.call(T.KW_PER_EXTRA, n)) return T.KW_PER_EXTRA[n] * ((mag == null ? 1 : mag) - 1);
    return NaN;   // I11 catches this (defect 3: cost('growth') missing => NaN)
  };
  const surcharge = (cls, k) => {
    const n = kwName(k), mag = kwMag(k);
    const tbl = T.CLS_SURCHARGE[cls];
    if (!tbl || !Object.prototype.hasOwnProperty.call(tbl, n)) return 0;
    const perStack = (T.CLS_SURCHARGE_PER_STACK[cls] || []).includes(n);
    return tbl[n] * (perStack ? (mag == null ? 1 : mag) : 1);
  };
  const typeCost = (cls, t) => ((T.TYPE_COST[cls] || {})[t] || 0);
  return { B_C, KW_SCALE, flatCost, surcharge, typeCost };
}

/* F5b for a template at one bucket. Returns { value, raw, clamped }.
 *
 * JUDGMENT CALL (reported): F5b's prose divides BOTH kwBudget and perStackCost by R[type],
 * but every worked example in the doc (aqua.ears.A, bird.eyes.D, bug.eyes.C, beast.eyes.A)
 * divides only kwBudget. The examples are what reproduce §3.11, so the examples win.
 */
function computeRaw(tpl, bucket, M, T, profile, bOverride) {
  const B_C = M.B_C;
  const B = bOverride === undefined ? B_C * T.S[bucket] : bOverride;
  const B_eff = B * T.SlotMod[tpl.slot];
  const R = T.R[tpl.t];
  if (!Number.isFinite(R)) return { value: NaN, raw: NaN, clamped: false, reason: `no R[${tpl.t}]` };
  const tc = M.typeCost(tpl.cls, tpl.t) * M.KW_SCALE;
  if (tpl.t === 'buff' || tpl.t === 'debuff') {
    let kwBudget = (B_eff - tc) / R;
    const hasAoe = tpl.k.some((k) => kwName(k) === 'aoe');
    if (hasAoe) kwBudget *= T.AOE_KWB;
    let flatRiders = 0;
    let scaling = null;
    for (const k of tpl.k) {
      const n = kwName(k);
      if (n === 'aoe') continue;                 // F5b aoe law: multiplicative only, no surcharge
      if (kwMag(k) === null && String(k).endsWith(':N')) { /* unreachable */ }
      if (/:N$/.test(k)) { scaling = n; continue; }
      flatRiders += (M.flatCost(k) + M.surcharge(tpl.cls, k));
    }
    /* the ":N" magnitude keyword is the one being sized; its class surcharge is a flat rider */
    if (scaling) flatRiders += M.surcharge(tpl.cls, scaling);
    if (!scaling) return { value: NaN, raw: NaN, clamped: false, reason: 'no :N scaling keyword on v=0 face' };
    const perStack = T.KW_PER_STACK[scaling];
    if (!Number.isFinite(perStack)) return { value: NaN, raw: NaN, clamped: false, reason: `no per-stack cost for ${scaling}` };
    const raw = (kwBudget - flatRiders * M.KW_SCALE) / (perStack * M.KW_SCALE);
    const value = Math.max(1, Math.floor(raw));
    return { value, raw, clamped: raw < 1, v0: true };
  }
  let KW = 0;
  for (const k of tpl.k) KW += (M.flatCost(k) + M.surcharge(tpl.cls, k));
  const raw = (B_eff - tc - KW * M.KW_SCALE) / R;
  const value = Math.max(1, Math.round(raw));
  return { value, raw, clamped: raw < 1, v0: false };
}

function computeVariants(design, M, T, profile) {
  const out = new Map();          // variantId -> { C, O, P }
  const monotoneLifts = [];
  const clampFloor = [];
  for (const cls of CLASS_ORDER) {
    for (const slot of SLOT_ORDER) {
      const family = (design.fam[cls] || {})[slot];
      if (!family) { hardFail('PARSE-3.11', `${cls}·${slot}`, 'family present', 'missing'); continue; }
      for (const letter of Object.keys(family).sort()) {
        const tpl = family[letter];
        if (tpl.spare || tpl.corrupt) continue;         // nothing authored / unparseable: nothing to derive
        const raws = {};
        for (const b of BUCKETS) {
          const r = computeRaw(tpl, b, M, T, profile);
          raws[b] = r;
          if (r.clamped) clampFloor.push({ variant: tpl.id, bucket: b, raw: round4(r.raw) });
          if (!Number.isFinite(r.value)) {
            hardFail('I11', `${tpl.id}@${b}`, 'finite value', String(r.value), r.reason || tpl.where);
          }
        }
        /* F6 monotone-by-construction */
        const v = {};
        v.C = Math.max(1, raws.C.value);
        v.O = Math.max(v.C + 1, raws.O.value);
        v.P = Math.max(v.O + 1, raws.P.value);
        for (const b of BUCKETS) {
          if (v[b] !== raws[b].value) {
            monotoneLifts.push({ variant: tpl.id, bucket: b, from: raws[b].value, to: v[b] });
          }
        }
        out.set(tpl.id, { tpl, aff: affineOf(tpl, M, T, profile), v, preRepair: { C: v.C, O: v.O, P: v.P }, raw: { C: round4(raws.C.raw), O: round4(raws.O.raw), P: round4(raws.P.raw) } });
      }
    }
  }
  return { variantValues: out, monotoneLifts, clampFloor };
}
const round4 = (x) => (Number.isFinite(x) ? Math.round(x * 1e4) / 1e4 : x);

/* F5b's `raw` is AFFINE in the die-level budget B — both the v>0 branch
 * ((B*SlotMod - TYPE_COST - KW)/R) and the v=0 branch (kwBudget/perStack) are B*m - c.
 * The runtime has to re-derive `v` at an arbitrary B, because §3.4a (gene ladder) and
 * §3.4b (coherence) both scale B per-Axie and neither can be pre-tabulated per bucket.
 * Rather than port F5b's whole cost table into engine.js — a second copy that would drift —
 * the generator probes its OWN computeRaw at B=0 and B=1 and ships the two coefficients.
 * One implementation of the formula, two consumers of its slope. */
function affineOf(tpl, M, T, profile) {
  const at = (B) => computeRaw(tpl, 'C', M, T, profile, B).raw;
  const r0 = at(0), r1 = at(1);
  return { m: round6(r1 - r0), c: round6(-r0), mode: tpl.t === 'buff' || tpl.t === 'debuff' ? 'f' : 'r' };
}
const round6 = (x) => (Number.isFinite(x) ? Math.round(x * 1e6) / 1e6 : x);

/* ================================================================= *
 * STAGE 6 — computeSignature()                                       *
 * ================================================================= */
function computeSignature(sig, M, T, profile) {
  const SIG_IMPORT_SCALE = M.B_C / T.B_REF;
  const v = Math.max(1, Math.round(sig.v * SIG_IMPORT_SCALE));
  return { p: sig.slot, t: sig.t, v: sig.t === 'debuff' || sig.t === 'buff' ? 0 : v, k: sig.k.slice(), r: sig.r, src: 'sig', name: sig.name, cls: sig.cls, legacy: sig.legacy, secret: sig.secret, key: sig.key, where: sig.where };
}

/* ================================================================= *
 * STAGE 3+5 — checkDesign() and REPAIR()                             *
 * ================================================================= */
function checkDirectionLaw(f, where) {
  /* `mana:N` is textually inside kwPure (§3.7a correction 2) but is NOT applied through
     addStatus: doFace() adds it to s.mana directly at engine.js:537, outside the status path.
     So it functions on every face type, exactly as §3.7's keyword table states
     ("Type dùng được: tất cả"). §3.7a's group-3 rule and §3.7's table contradict each other
     on this one keyword; the engine mechanism both sections describe settles it. */
  const pure = f.k.filter((k) => !KW_NOT_PURE.has(kwName(k)) && kwName(k) !== 'mana');
  const t = f.t;
  for (const k of pure) {
    const n = kwName(k);
    if (t === 'dmg' || t === 'debuff') {
      if (KWPURE_ALLY.has(n)) hardFail('I8', where, `no ally-kwPure on ${t}`, k, '§3.7a: you would buff the enemy');
    } else if (t === 'shield' || t === 'heal' || t === 'buff') {
      if (KWPURE_FOE.has(n)) hardFail('I8', where, `no foe-kwPure on ${t}`, k, '§3.7a: you would debuff your ally');
    } else if (t === 'mana' || t === 'summon' || t === 'poison') {
      hardFail('I8', where, `no kwPure at all on ${t}`, k, '§3.7a group 3: silently inert');
    }
  }
}
function checkCantripLaw(f, where) {
  if (!f.k.some((k) => kwName(k) === 'cantrip')) return;
  const hasAoe = f.k.some((k) => kwName(k) === 'aoe');
  if ((f.t === 'dmg' || f.t === 'poison' || f.t === 'debuff') && !hasAoe) {
    hardFail('I9', where, 'cantrip only on self-targetable type or with aoe', `cantrip on single-target ${f.t}`, 'E7');
  }
}
function checkKeywordWhitelist(f, where) {
  for (const k of f.k) {
    const n = kwName(k);
    if (n === 'shieldself') { hardFail('I10', where, 'shieldself used 0 times', k, '§3.7: never implemented'); continue; }
    if (!KW_WHITELIST.has(n)) hardFail('I10', where, 'keyword in §3.7 whitelist', k, null);
  }
}

/* materialise a variant template at a magnitude exactly as the engine will see it:
   buff/debuff carry v=0 and put the magnitude into the ':N' keyword. */
function instFace(tpl, mag) {
  const v0 = tpl.t === 'buff' || tpl.t === 'debuff';
  return { t: tpl.t, v: v0 ? 0 : mag, k: tpl.k.map((x) => x.replace(/:N$/, ':' + mag)) };
}

/* §3.5d REPAIR — signature<->variant collisions inside one family, deterministic order.
   JUDGMENT CALL (reported): §3.5d says "for bucket in [C,O,P,X] có mặt trong F". Taken as
   "every bucket", REPAIR bumps (variant,bucket) instances that NO catalog part reaches --
   including all 11 spares -- and those phantom tuples cascade into real bumps (16 instead of
   the 2 the doc predicts). §3.5d-bis's SPREAD pass says "reachableVariantInstances", so this
   implementation repairs REACHABLE instances only. --repair-all-buckets restores the literal
   reading. */
function repairPass(design, variantValues, sigFaces, T, opts, reachable) {
  const repairLog = [];
  let collisions = 0;
  for (const cls of CLASS_ORDER) {
    for (const slot of SLOT_ORDER) {
      const family = (design.fam[cls] || {})[slot];
      if (!family) continue;
      const S = new Set();
      for (const f of sigFaces) if (f.cls === cls && f.p === slot) S.add(repairTuple({ t: f.t, v: f.v, k: f.k }));
      for (const letter of Object.keys(family).sort()) {
        const rec = variantValues.get(family[letter].id);
        if (!rec) continue;
        const live = reachable.get(rec.tpl.id) || new Set();
        for (const b of BUCKETS) {
          if (!opts.repairAllBuckets && !live.has(b)) continue;
          let bumps = 0;
          let tup = repairTuple(instFace(rec.tpl, rec.v[b]));
          while (S.has(tup) && bumps < T.REPAIR_MAX_BUMP) {
            rec.v[b] += 1; bumps++;
            tup = repairTuple(instFace(rec.tpl, rec.v[b]));
          }
          if (S.has(tup)) {
            hardFail('I6', `${rec.tpl.id}@${b}`, 'no signature collision after <=2 bumps',
              `still collides on ${tup}`, `family ${cls}·${slot}`);
          }
          S.add(tup);
          if (bumps > 0) { collisions++; repairLog.push({ variant: rec.tpl.id, bucket: b, bumps }); }
        }
        /* property 4: re-assert monotone after bumps */
        if (!(rec.v.C < rec.v.O && rec.v.O < rec.v.P)) {
          rec.v.O = Math.max(rec.v.O, rec.v.C + 1);
          rec.v.P = Math.max(rec.v.P, rec.v.O + 1);
          repairLog.push({ variant: rec.tpl.id, bucket: '*', bumps: 0, note: 'monotone re-enforced after repair' });
        }
      }
    }
  }
  if (collisions > T.REPAIR_MAX_COLLISIONS) {
    hardFail('I6', 'REPAIR', `<= ${T.REPAIR_MAX_COLLISIONS} collisions`, String(collisions),
      'B[C] may have been lowered far enough that v collapses onto signature faces (§3.5d)');
  }
  return { repairLog, collisions };
}


/* §3.5d-bis SPREAD — R8 at SLOT scope, run after REPAIR.
   Three steps with different powers, exactly as specified:
     1. the 50 legacy faces are locked first and are NEVER moved (AC-7c outranks R8);
     2. reachable variant instances are only RECORDED — a clash here is a §3.11 design fault
        (R7), not something the generator is allowed to paper over with a value bump;
     3. the 31 authored signatures (13 Addendum + 18 Secret) may be nudged, at most
        SPREAD_MAX_BUMP.
   Deterministic order: legacy by partKey, instances by (variantId, C/O/P), authored by name. */
function bumpFaceValue(f) {
  /* buff/debuff carry v=0 structurally; their magnitude lives in the ':N' keyword string. */
  if (f.t !== 'buff' && f.t !== 'debuff') { f.v += 1; return true; }
  for (let i = f.k.length - 1; i >= 0; i--) {
    const mag = kwMag(f.k[i]);
    if (mag != null) { f.k[i] = kwName(f.k[i]) + ':' + (mag + 1); return true; }
  }
  return false;
}

function spreadPass(sigFaces, variantValues, reachable, T, partsPerSlot) {
  const log = [];
  for (const slot of SLOT_ORDER) {
    const U = new Map();

    /* STEP 1 — legacy, locked */
    for (const f of sigFaces.filter((x) => x.p === slot && x.legacy)
      .sort((a, b) => (a.key < b.key ? -1 : 1))) {
      const tup = repairTuple(f);
      if (U.has(tup)) {
        hardFail('R8-LEGACY', f.key, 'no other legacy face in slot ' + slot + ' holds "' + tup + '"',
          'collides with ' + U.get(tup),
          'both are FACE_POOL legacy and neither may move (AC-7c) — SIG_LIFT should have separated them');
      }
      U.set(tup, f.key);
    }

    /* STEP 2 — reachable variant instances, recorded only, never bumped */
    const insts = [];
    for (const [vid, buckets] of reachable) {
      const rec = variantValues.get(vid);
      if (!rec || rec.tpl.slot !== slot) continue;
      for (const b of BUCKETS) if (buckets.has(b)) insts.push({ rec, b });
    }
    insts.sort((x, y) => (x.rec.tpl.id < y.rec.tpl.id ? -1 : x.rec.tpl.id > y.rec.tpl.id ? 1
      : BUCKETS.indexOf(x.b) - BUCKETS.indexOf(y.b)));
    for (const inst of insts) {
      const tup = repairTuple(instFace(inst.rec.tpl, inst.rec.v[inst.b]));
      if (U.has(tup)) {
        hardFail('R8-VARIANT', inst.rec.tpl.id + '@' + inst.b,
          'nothing else in slot ' + slot + ' holds "' + tup + '"',
          'collides with ' + U.get(tup),
          'SPREAD may not bump a variant — fix the keyword set in §3.11 (R7) or the §3.12 assignment');
      }
      U.set(tup, inst.rec.tpl.id + '@' + inst.b);
    }

    /* STEP 3 — the 31 authored signatures, movable by at most SPREAD_MAX_BUMP */
    for (const f of sigFaces.filter((x) => x.p === slot && !x.legacy)
      .sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : (a.key < b.key ? -1 : 1)))) {
      let bumps = 0;
      let tup = repairTuple(f);
      while (U.has(tup) && bumps < T.SPREAD_MAX_BUMP) {
        if (!bumpFaceValue(f)) break;
        bumps++;
        tup = repairTuple(f);
      }
      if (U.has(tup)) {
        hardFail('R8-UNRESOLVED', f.key,
          'a free tuple in slot ' + slot + ' within ' + T.SPREAD_MAX_BUMP + ' bumps',
          'still collides with ' + U.get(tup) + ' on "' + tup + '"',
          (f.secret ? '§3.10 secret' : '§3.3b addendum') + ' face — needs a design change');
      }
      U.set(tup, f.key);
      if (bumps) log.push({ face: f.key, name: f.name, bumps, v: f.v, k: f.k.slice() });
    }

    /* closing identity of §3.5d-bis: one distinct tuple per part in the slot */
    const nParts = partsPerSlot[slot] || 0;
    if (U.size !== nParts) {
      hardFail('AC-9c', 'slot ' + slot, '|U| === ' + nParts + ' (parts in the slot)', String(U.size),
        '§3.5d-bis closing assertion — some parts still share an engine tuple');
    }
  }
  return log;
}

/* ================================================================= *
 * MAIN DERIVATION — pure: (catalogRows, md, tuning, opts) -> report   *
 * ================================================================= */
function derive(catalogRows, md, T, opts) {
  const profile = opts.profile;
  const M = makeMath(T, profile);

  /* 1. catalog */
  const identities = loadCatalog(catalogRows);

  /* 2. design */
  const { sigs, counts: sigCounts } = parseSignatures(md);
  const design = parseFamilyVariant(md);
  const pv = parsePartVariant(md);

  /* --- parse cross-checks against the figures the doc states --- */
  if (sigs.size !== 81) hardFail('I3', 'SIGNATURE_FACE', '81 keys', String(sigs.size), `parsed: ${sigCounts.legacy} legacy + ${sigCounts.addendum} addendum + ${sigCounts.secret} secret`);
  if (sigCounts.legacy !== 50) hardFail('PARSE-3.3a', '§3.3a', '50 rows', String(sigCounts.legacy));
  if (sigCounts.addendum !== 13) hardFail('PARSE-3.3b', '§3.3b', '13 rows', String(sigCounts.addendum));
  if (sigCounts.secret !== 18) hardFail('PARSE-3.10', '§3.10', '18 rows', String(sigCounts.secret));
  if (design.nVar !== 158) hardFail('PARSE-3.11', '§3.11', '158 variants', String(design.nVar));
  if (pv.map.size !== 204) hardFail('I1', 'PART_VARIANT', '204 keys', String(pv.map.size));
  if (identities.length !== 285) hardFail('CATALOG', 'parts_full_source.json', '285 identities', String(identities.length));
  for (const [cls, c] of Object.entries(pv.perClass)) {
    if (c.stated !== c.parsed) hardFail('PARSE-3.12', `§3.12 ${cls.toUpperCase()}`, `${c.stated} assignments (stated in the header)`, `${c.parsed} parsed`);
  }

  /* I3 — disjoint, union = 285 */
  const catalogKeys = new Set(identities.map((i) => i.key));
  for (const k of sigs.keys()) if (pv.map.has(k)) hardFail('I3', k, 'SIGNATURE ∩ PART_VARIANT = {}', 'present in both');
  const union = new Set([...sigs.keys(), ...pv.map.keys()]);
  if (union.size !== 285) hardFail('I3', 'SIGNATURE ∪ PART_VARIANT', '285', String(union.size));

  /* --- catalog cross-check: every design row must exist at the stated class+slot --- */
  const byKey = new Map(identities.map((i) => [i.key, i]));
  const missing = [];
  for (const [k, a] of pv.map) {
    const id = byKey.get(k);
    if (!id) { missing.push({ table: '§3.12', key: k, line: a.line }); continue; }
    if (id.bucket !== a.statedBucket) {
      hardFail('CATALOG-BUCKET', k, `bucket ${id.bucket} (from catalog stages {${[...id.stages].sort().join(',')}})`, `§3.12 says (${a.statedBucket})`, `doc line ${a.line}`);
    }
  }
  for (const [k, s] of sigs) if (!byKey.has(k)) missing.push({ table: s.where, key: k });
  for (const m of missing) hardFail('CATALOG-MISSING', m.key, 'present in parts_full_source.json at that class+slot', 'absent', m.table);
  const unassigned = identities.filter((i) => !sigs.has(i.key) && !pv.map.has(i.key));
  for (const u of unassigned) hardFail('COVERAGE', u.key, 'assigned to a signature or a variant', 'unassigned', `bucket ${u.bucket}`);

  /* 3. checkDesign — direction law / cantrip law / whitelist / class identity */
  for (const cls of CLASS_ORDER) {
    for (const slot of SLOT_ORDER) {
      const family = (design.fam[cls] || {})[slot];
      if (!family) continue;
      for (const letter of Object.keys(family).sort()) {
        const tpl = family[letter];
        const f = { t: tpl.t, k: tpl.k.map((k) => k.replace(/:N$/, ':1')) };
        checkDirectionLaw(f, tpl.id);
        checkCantripLaw(f, tpl.id);
        checkKeywordWhitelist(f, tpl.id);
        const banned = CLASS_TYPE_BAN[cls] || [];
        if (banned.includes(tpl.t)) hardFail('I21', tpl.id, `${cls} may not use type ${tpl.t}`, tpl.t, tpl.where);
        if (tpl.k.length > 3) hardFail('I20', tpl.id, '<= 3 keywords on a variant', String(tpl.k.length), tpl.where);
      }
    }
  }
  for (const s of sigs.values()) {
    checkDirectionLaw({ t: s.t, k: s.k }, s.where);
    checkCantripLaw({ t: s.t, k: s.k }, s.where);
    checkKeywordWhitelist({ t: s.t, k: s.k }, s.where);
  }

  /* R1 — injectivity inside a bucket of a family */
  const r1 = new Map();
  for (const a of pv.map.values()) {
    const id = byKey.get(a.key);
    const b = id ? id.bucket : a.statedBucket;
    const key = `${a.cls}.${a.slot}|${b}|${a.letter}`;
    if (r1.has(key)) hardFail('I4', key, 'one part per (family, bucket, variant)', `${r1.get(key)} and ${a.name}`, 'R1');
    else r1.set(key, a.name);
  }

  /* 4. computeVariants */
  const { variantValues, monotoneLifts, clampFloor } = computeVariants(design, M, T, profile);

  /* 6. computeSignature */
  const sigFaces = [...sigs.values()].sort((a, b) => (a.key < b.key ? -1 : 1)).map((s) => computeSignature(s, M, T, profile));
  const sigByKey = new Map(sigFaces.map((f) => [f.key, f]));

  /* reachable (variant, bucket) instances — needed by REPAIR and by R7/R8 */
  const reachable = new Map();
  for (const a of pv.map.values()) {
    const id = byKey.get(a.key);
    const b = id ? id.bucket : a.statedBucket;
    const vid = `${a.cls}.${a.slot}.${a.letter}`;
    if (!reachable.has(vid)) reachable.set(vid, new Set());
    reachable.get(vid).add(b);
  }

  /* 6b. SIG_LIFT (§3.3c, F7b) — stop the integer floor from merging distinct legacy faces.
     Group by (p, t, sortedKeys) WITHOUT cls, ascending by pool value, tie-break by name. */
  const sigLifts = [];
  {
    const groups = new Map();
    for (const f of sigFaces) {
      if (f.t === 'buff' || f.t === 'debuff') continue;      // v is structurally 0
      const g = `${f.p}|${f.t}|${sortedKw(f.k)}`;
      if (!groups.has(g)) groups.set(g, []);
      groups.get(g).push(f);
    }
    for (const g of [...groups.keys()].sort()) {
      const mem = groups.get(g);
      const pool = new Map(mem.map((f) => [f.key, sigs.get(f.key).v]));
      mem.sort((a, b) => (pool.get(a.key) - pool.get(b.key)) || (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
      let prev = -Infinity;
      for (const f of mem) {
        const natural = Math.max(1, Math.round(pool.get(f.key) * M.KW_SCALE));
        const lifted = Math.max(prev + 1, natural);
        if (lifted - natural > T.SIG_LIFT_MAX) {
          hardFail('I25', f.key, `SIG_LIFT <= SIG_LIFT_MAX (${T.SIG_LIFT_MAX})`, String(lifted - natural),
            `group ${g}: pool v=${pool.get(f.key)} would have to move ${natural} -> ${lifted}`);
        }
        if (lifted !== f.v) sigLifts.push({ face: f.key, group: g, pool: pool.get(f.key), from: natural, to: lifted });
        f.v = lifted;
        prev = lifted;
      }
      /* I25 second half: strictly increasing inside every group */
      for (let i = 1; i < mem.length; i++) {
        if (!(mem[i - 1].v < mem[i].v)) {
          hardFail('I25', g, 'strictly increasing v inside the group', `${mem[i - 1].name}=${mem[i - 1].v}, ${mem[i].name}=${mem[i].v}`);
        }
      }
    }
  }

  /* 5. REPAIR */
  let repair = { repairLog: [], collisions: 0 };
  if (!opts.noRepair) repair = repairPass(design, variantValues, sigFaces, T, opts, reachable);

  /* 5b. SPREAD (§3.5d-bis, R8) — slot-scope, after REPAIR, before the faces are materialised */
  let spreadLog = [];
  if (!opts.noR7) {
    const partsPerSlot = {};
    for (const i of identities) partsPerSlot[i.slot] = (partsPerSlot[i.slot] || 0) + 1;
    spreadLog = spreadPass(sigFaces, variantValues, reachable, T, partsPerSlot);
  }

  /* I7 — monotone on all 158 variants (after repair) */
  for (const [id, rec] of variantValues) {
    if (!(rec.v.C < rec.v.O && rec.v.O < rec.v.P)) {
      hardFail('I7', id, 'v(C) < v(O) < v(P)', `${rec.v.C} / ${rec.v.O} / ${rec.v.P}`, rec.tpl.where);
    }
  }

  /* --- resolve all 285 parts to concrete faces --- */
  const faces = [];
  const excluded = [];   // parts whose variant row could not be parsed
  for (const id of identities) {
    const s = sigByKey.get(id.key);
    if (s) { faces.push({ ...s, p: s.p, bucket: id.bucket, partKey: id.key, src: 'sig' }); continue; }
    const a = pv.map.get(id.key);
    if (!a) continue;                                  // already reported by COVERAGE
    const rec = variantValues.get(`${a.cls}.${a.slot}.${a.letter}`);
    if (!rec) { excluded.push({ key: id.key, variant: `${a.cls}.${a.slot}.${a.letter}` }); continue; }
    const isV0 = rec.tpl.t === 'buff' || rec.tpl.t === 'debuff';
    const mag = rec.v[id.bucket];
    const k = rec.tpl.k.map((x) => x.replace(/:N$/, ':' + mag));
    faces.push({
      partKey: id.key, cls: a.cls, p: a.slot, t: rec.tpl.t, v: isV0 ? 0 : mag,
      k, r: Math.min(3, T.SCARCITY_RFLOOR[id.bucket]), src: 'var',
      variant: a.letter, variantId: rec.tpl.id, bucket: id.bucket, name: a.name,
    });
  }

  /* R7 / R8 — only when not running the pre-R7 baseline */
  const r7 = { violations: [] };
  if (!opts.noR7) {
    for (const slot of SLOT_ORDER) {
      const seenKwSet = new Map();
      const reachable = [...pv.map.values()].filter((a) => a.slot === slot)
        .map((a) => variantValues.get(`${a.cls}.${a.slot}.${a.letter}`)).filter(Boolean);
      const uniq = new Map();
      for (const rec of reachable) uniq.set(rec.tpl.id, rec);
      for (const rec of [...uniq.values()].sort((a, b) => (a.tpl.id < b.tpl.id ? -1 : 1))) {
        const t = kwSetTuple({ t: rec.tpl.t, k: rec.tpl.k });
        if (seenKwSet.has(t)) {
          r7.violations.push({ slot, a: seenKwSet.get(t), b: rec.tpl.id, tuple: t });
          if (r7.violations.length <= 12) hardFail('I5', rec.tpl.id, `slot-wide unique (t, sortedKeys) in ${slot}`, `collides with ${seenKwSet.get(t)} on "${t}"`, 'R7 (§3.5c) — 77 keyword sets still to be authored');
        } else seenKwSet.set(t, rec.tpl.id);
      }
    }
    if (r7.violations.length > 12) {
      hardFail('I5', 'R7 slot-wide keyword-set uniqueness', '0 duplicate (t, sortedKeys) per slot',
        `${r7.violations.length} duplicates (only the first 12 listed above)`,
        '§3.5c-bis: 77 new keyword sets are still to be authored (work item N17). This gate is RED on purpose.');
    }
  }

  /* I24 / AC-34b — per slot, no reachable variant template may share (t, sortedKeys) with any
     of the 50 legacy signature faces. Forbidden-set sizes are COMPUTED from the legacy roster,
     never hand-listed, and cross-checked against the counts §8 states. */
  const I24_EXPECT = { mouth: 9, horn: 10, back: 5, tail: 11, eyes: 6, ears: 3 };
  const forbidden = {};
  for (const slot of SLOT_ORDER) {
    forbidden[slot] = new Map();
    for (const f of sigFaces) {
      if (!f.legacy || f.p !== slot) continue;
      const t = kwSetTuple({ t: f.t, k: f.k });
      if (!forbidden[slot].has(t)) forbidden[slot].set(t, []);
      forbidden[slot].get(t).push(f.name);
    }
    if (forbidden[slot].size !== I24_EXPECT[slot]) {
      hardFail('AC-34b', `slot ${slot}`, `${I24_EXPECT[slot]} forbidden legacy keyword sets`,
        String(forbidden[slot].size), [...forbidden[slot].keys()].sort().join(' | '));
    }
  }
  let i24 = 0;
  for (const slot of SLOT_ORDER) {
    for (const a of [...pv.map.values()].filter((x) => x.slot === slot)) {
      const rec = variantValues.get(`${a.cls}.${a.slot}.${a.letter}`);
      if (!rec) continue;
      const t = kwSetTuple({ t: rec.tpl.t, k: rec.tpl.k });
      if (forbidden[slot].has(t)) {
        i24++;
        if (i24 <= 6) {
          hardFail('I24', rec.tpl.id, `no legacy signature in slot ${slot} uses "${t}"`,
            `collides with legacy ${forbidden[slot].get(t).join(', ')}`, rec.tpl.where);
        }
      }
    }
  }
  if (i24 > 6) hardFail('I24', 'variant vs legacy', 'empty intersection per slot', `${i24} colliding assignments (first 6 listed)`, null);

  /* --- THE COUNT: engine-distinct (p, t, v, k) --- */
  const perSlot = {};
  for (const slot of SLOT_ORDER) perSlot[slot] = { parts: 0, distinct: 0, sig: 0, var: 0, lost: 0, collisions: [] };
  const global = new Set();
  const bySlot = {};
  for (const slot of SLOT_ORDER) bySlot[slot] = new Map();
  for (const f of faces.slice().sort((a, b) => (a.partKey < b.partKey ? -1 : 1))) {
    const s = perSlot[f.p];
    if (!s) { hardFail('SLOT', f.partKey, 'known slot', f.p); continue; }
    s.parts++;
    if (f.src === 'sig') s.sig++; else s.var++;
    const tup = engineTuple(f);
    global.add(tup);
    const m = bySlot[f.p];
    if (m.has(tup)) { s.lost++; s.collisions.push({ tuple: tup, a: m.get(tup), b: f.partKey }); }
    else m.set(tup, f.partKey);
  }
  for (const slot of SLOT_ORDER) perSlot[slot].distinct = bySlot[slot].size;
  const distinctEngineFaces = global.size;
  const distinctIdentity = new Set(faces.map((f) => `${f.cls}|${engineTuple(f)}`)).size;

  /* --- totals --- */
  const nBucket = { C: 0, O: 0, P: 0, X: 0 };
  for (const a of pv.map.values()) {
    const id = byKey.get(a.key);
    nBucket[id ? id.bucket : a.statedBucket]++;
  }
  const usedVariants = new Set([...pv.map.values()].map((a) => `${a.cls}.${a.slot}.${a.letter}`));
  const spareList = design.order.filter((t) => t.spare).map((t) => t.id).sort();
  /* the §3.11 "reachable" column and the §3.12 assignments are two independent statements of
     the same fact — cross-check them rather than trusting either */
  for (const t of design.order) {
    if (t.spare && usedVariants.has(t.id)) {
      hardFail('REACHABLE', t.id, '§3.11 marks it *(spare)* / — so §3.12 must not assign to it', 'assigned in §3.12', t.where);
    }
    if (!t.spare && !usedVariants.has(t.id)) {
      hardFail('REACHABLE', t.id, '§3.11 marks it reachable so §3.12 must assign a part to it', 'no part assigned', t.where);
    }
  }

  /* I1 / I2 / I13 */
  if (nBucket.C + nBucket.O + nBucket.P !== 204) {
    hardFail('I1', 'nC+nO+nP', '204', String(nBucket.C + nBucket.O + nBucket.P), `nC=${nBucket.C} nO=${nBucket.O} nP=${nBucket.P}`);
  }
  const primeSig = [...sigs.keys()].filter((k) => (byKey.get(k) || {}).bucket === 'P');
  if (nBucket.P !== 18 - primeSig.length) {
    hardFail('I2', 'nP', `18 - |Prime ∩ Signature| = ${18 - primeSig.length}`, String(nBucket.P), `Prime signatures: ${primeSig.join(', ')}`);
  }
  if (spareList.length > T.SPARE_MAX) {
    hardFail('I13', 'spares', `<= ${T.SPARE_MAX}`, String(spareList.length), spareList.join(' · '));
  }
  const spareStatedSorted = pv.spareStated.slice().sort();
  if (JSON.stringify(spareList) !== JSON.stringify(spareStatedSorted)) {
    hardFail('I13', 'spareList', spareStatedSorted.join(' · ') || '(none parsed)', spareList.join(' · '), '§3.12 stated set vs computed set');
  }

  /* I14 — B_CAP0 < B[C] + GENE_STEP*GENE_MAX (F1a, pre-revision-3 form) */
  const S_MAX = T.S.P;
  const G_MAX = 1 + T.SG_STEP * 7;
  const B_PROD = T.B_C.production;          // design-argument invariants are profile-independent
  const B_CAP0 = B_PROD * S_MAX * G_MAX;
  const playCeil = B_PROD + T.GENE_STEP * T.GENE_MAX;
  /* I14 — WITHDRAWN. F1a's "money < play" inequality was revoked at revision 3 (§3.4-bis,
     F1b-α) when the product owner accepted pay-to-win, and B_CAP0 was redefined as
     B[C]*S_MAX*G_MAX, which necessarily violates it. §6f now strikes I14 through.
     Reported as an informational line so the quantity stays visible; I16 is its replacement. */
  if (!(B_CAP0 < playCeil)) {
    finding('I14-withdrawn', `I14 (withdrawn): B_CAP0 = ${round4(B_CAP0)} >= B[C] + GENE_STEP*GENE_MAX = ${round4(playCeil)} — money buys more than play earns. Not a gate; I16 (SPREAD_OWN < ${T.SPREAD_OWN_MAX}) replaces it.`);
  }
  /* I15 — SBC_CAP <= 0.125*30 / (0.267*k/2.0) */
  const i15Bound = 0.125 * 30 / (0.267 * T.HANDICAP_K / 2.0);
  if (!(T.SBC_CAP <= i15Bound)) {
    hardFail('I15', 'SBC_CAP', `<= ${round4(i15Bound)}`, String(T.SBC_CAP), '§3.9c-bis handicap <= -20%');
  }
  /* I16 (revision-3 replacement for I14) */
  const SPREAD_OWN = S_MAX * G_MAX;
  if (!(SPREAD_OWN < T.SPREAD_OWN_MAX)) {
    hardFail('I16', 'SPREAD_OWN', `< ${T.SPREAD_OWN_MAX}`, String(round4(SPREAD_OWN)), 'S_MAX * G_MAX');
  }
  /* I23 */
  if (!(T.B_CAP_RUN * 1.018 <= T.TTK_CEIL_T3 * T.HERO_T3_AVG_FACE)) {
    hardFail('I23', 'B_CAP_RUN', `* 1.018 <= ${round4(T.TTK_CEIL_T3 * T.HERO_T3_AVG_FACE)}`, String(round4(T.B_CAP_RUN * 1.018)), 'TTK ceiling');
  }
  for (const e of excluded) {
    hardFail('PARSE-3.11', e.key, `a usable face from variant ${e.variant}`, 'variant row unparseable',
      'this part is EXCLUDED from every count below');
  }

  /* AC-9b (BLOCKING per §8): all 285 parts must differ at (cls, p, t, v, k) */
  if (excluded.length === 0 && distinctIdentity !== 285) {
    const seenId = new Map(); const dupes = [];
    for (const f of faces.slice().sort((a, b) => (a.partKey < b.partKey ? -1 : 1))) {
      const t = `${f.cls}|${engineTuple(f)}`;
      if (seenId.has(t)) dupes.push(`${f.partKey} == ${seenId.get(t)} [${t}]`); else seenId.set(t, f.partKey);
    }
    hardFail('AC-9b', 'identity-distinct faces', '285', String(distinctIdentity), dupes.join(' | '));
  }

  /* I17 — SPREAD_OWN must stay under the cap at every gene tier g in [0, GENE_MAX] */
  for (let g = 0; g <= T.GENE_MAX; g++) {
    /* gene tier is an additive run-time budget term, so it cancels out of the ownership
       ratio; assert that explicitly rather than assuming it. */
    const hi = Math.min(B_PROD * S_MAX * G_MAX, T.B_CAP_RUN - T.GENE_STEP * g) + T.GENE_STEP * g;
    const lo = Math.min(B_PROD * T.S.C * 1.0, T.B_CAP_RUN - T.GENE_STEP * g) + T.GENE_STEP * g;
    const ratio = hi / lo;
    if (!(ratio < T.SPREAD_OWN_MAX)) {
      hardFail('I17', `gene tier g=${g}`, `SPREAD_OWN(g) < ${T.SPREAD_OWN_MAX}`, String(round4(ratio)), 'F1b / §3.4-bis');
    }
  }

  /* I18 / AC-36 — the §3.4b SUPPRESS pass. Deterministic order (class asc -> letter), fixed
     candidate order. The constraint is slot-GLOBAL: a replacement must not land on any set
     already present in the slot, suppressed or not, variant or signature. */
  const SUPPRESSION = parseSuppression(md);
  const KW_SUPPRESS_THRESHOLD = T.KW_SUPPRESS_THRESHOLD;
  const matchSource = (kw) => SUPPRESSION.sources.find((sr) =>
    sr === kw || (sr.endsWith(':*') && kwName(kw) === sr.slice(0, -2)));
  const suppressLog = [];
  const overThreshold = new Set();
  {
    const rawCost = (k) => {
      const n = kwName(k), mag = kwMag(k);
      if (Object.prototype.hasOwnProperty.call(T.KW_FLAT, n)) return T.KW_FLAT[n];
      if (Object.prototype.hasOwnProperty.call(T.KW_PER_STACK, n)) return T.KW_PER_STACK[n] * (mag == null ? 1 : mag);
      if (Object.prototype.hasOwnProperty.call(T.KW_PER_EXTRA, n)) return T.KW_PER_EXTRA[n] * ((mag == null ? 1 : mag) - 1);
      return 0;
    };
    for (const slot of SLOT_ORDER) {
      const USED = new Set();
      for (const f of sigFaces) if (f.p === slot) USED.add(kwSetTuple({ t: f.t, k: f.k }));
      const live = [];
      for (const [vid, buckets] of reachable) {
        const rec = variantValues.get(vid);
        if (!rec || rec.tpl.slot !== slot || !buckets.size) continue;
        live.push(rec.tpl);
        USED.add(kwSetTuple({ t: rec.tpl.t, k: rec.tpl.k }));
      }
      live.sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
      for (const tpl of live) {
        const hasCantrip = tpl.k.some((k) => kwName(k) === 'cantrip');
        let cur = tpl.k.slice();
        for (const kw of tpl.k) {
          /* The doc states the suppressible set TWICE and the two statements disagree: the rule
             is "cost(k) > KW_SUPPRESS_THRESHOLD", but the enumerated list and SUPPRESS_CANDIDATES
             cover only 8 keywords, and §3.4b explicitly exempts weaken/thorns/vulnerable/blind/
             multi:2 which exceed the threshold at magnitude >= 3. The enumeration is the design
             input the doc actually owns, so it wins; the mismatch is reported as a finding. */
          const src = matchSource(kw);
          if (!src) {
            if (rawCost(kw) > KW_SUPPRESS_THRESHOLD) overThreshold.add(`${kw} (${round4(rawCost(kw))})`);
            continue;
          }
          const grp = TYPE_GROUP[tpl.t];
          if (!grp) { hardFail('I18', tpl.id, `a known type group for "${tpl.t}"`, 'none', '§3.4b typeGroup A/B/C'); continue; }
          const cands = SUPPRESSION.cand[src][grp];
          if (!cands || !cands.length) {
            hardFail('I18', tpl.id, `SUPPRESS_CANDIDATES[${src}][${grp}] to be non-empty`,
              'the doc marks that branch as "—" (does not exist)',
              `but variant ${tpl.id} is type ${tpl.t} (group ${grp}) and carries "${kw}" — §3.4b says this combination is never authored`);
            continue;
          }
          /* E7 safety carve-out: never touch aoe on a cantrip dmg/poison/debuff face */
          if (kwName(kw) === 'aoe' && hasCantrip && ['dmg', 'poison', 'debuff'].includes(tpl.t)) continue;
          const tried = [];
          let accepted = null;
          for (const cand of cands) {
            const trial = cur.map((x) => (x === kw ? cand : x));
            const uniq = [...new Set(trial)];
            tried.push(cand);
            if (uniq.length === 0) continue;                       // never empty the set
            if (uniq.length > 3) continue;                         // I20
            const before = failures.length;
            checkDirectionLaw({ t: tpl.t, k: uniq.map((x) => x.replace(/:N$/, ':1')) }, tpl.id);
            checkCantripLaw({ t: tpl.t, k: uniq }, tpl.id);
            const legal = failures.length === before;
            failures.length = before;                              // probe only, never records
            if (!legal) continue;
            const tup = kwSetTuple({ t: tpl.t, k: uniq });
            if (USED.has(tup)) continue;
            accepted = { k: uniq, tup, cand };
            break;
          }
          if (!accepted) {
            hardFail('I18-UNRESOLVED', tpl.id,
              `a legal replacement for "${kw}" that is free in slot ${slot}`,
              `all candidates rejected: ${tried.join(', ')} (group ${TYPE_GROUP[tpl.t]})`,
              'every candidate was illegal (§3.7a / E7 / I20) or already taken in this slot (§3.4b)');
            continue;
          }
          USED.add(accepted.tup);
          suppressLog.push({ variant: tpl.id, from: kw, to: accepted.cand, k: accepted.k });
          cur = accepted.k;
        }
        /* §3.4b says the budget freed by swapping an expensive keyword for a cheap one is
           REFUNDED into v ("chenh lech ngan sach hoan vao v"), so a suppressed face is not
           just a different keyword set — it is a different affine model. Ship both, because
           only the runtime knows a given Axie's purity. */
        if (cur.join('\u0000') !== tpl.k.join('\u0000')) {
          const rec = variantValues.get(tpl.id);
          if (rec) rec.sup = { k: cur.slice(), aff: affineOf({ ...tpl, k: cur.slice() }, M, T, profile) };
        }
      }
    }
  }

  if (overThreshold.size) {
    finding('suppress-threshold', `§3.4b: ${overThreshold.size} keyword form(s) `
      + `cost more than KW_SUPPRESS_THRESHOLD (${KW_SUPPRESS_THRESHOLD}) but are not in SUPPRESS_SOURCES: `
      + `${[...overThreshold].sort().join(', ')}. Harmless — §3.4b makes the enumeration the definition — `
      + `but the leftover threshold constant is now dead and could mislead.`);
  }

  /* I19 — clampFloor must not grow more than 20% against the committed snapshot */
  if (profile === 'production' && opts.prevClampFloor != null) {
    const cap = Math.ceil(opts.prevClampFloor * 1.2);
    if (clampFloor.length > cap) {
      hardFail('I19', 'clampFloor', `<= ${cap} (previous snapshot ${opts.prevClampFloor} + 20%)`,
        String(clampFloor.length), 'expensive keywords are pushing faces onto the max(1, .) floor (§3.5c-bis)');
    }
  }

  /* I11 — no NaN/undefined/Infinity anywhere in the emitted faces */
  for (const f of faces) {
    if (!Number.isFinite(f.v) || !Number.isFinite(f.r) || !f.t || !Array.isArray(f.k)) {
      hardFail('I11', f.partKey, 'finite v/r, string t, array k', JSON.stringify({ v: f.v, r: f.r, t: f.t, k: f.k }));
    }
    for (const k of f.k) if (/NaN|undefined|Infinity/.test(String(k))) hardFail('I11', f.partKey, 'clean keyword string', k);
  }

  /* I12 / AC-7 — NOT MEASURABLE any more. §3.11 was consolidated and the C/O/P columns were
     deliberately removed (they were the hand-maintained cells that caused defects 1/6/7).
     There is nothing left in the doc to compare against; AC-7d (--check against the committed
     snapshot) is now the only regression gate on the numbers. */
  const cellDiffs = [];
  const ac7Measurable = [...variantValues.values()].some((r) => r.tpl.tabled);

  return {
    profile, identities, sigs, sigFaces, design, pv, variantValues, faces, byKey,
    monotoneLifts, clampFloor, repair, r7, cellDiffs, sigLifts, excluded, spreadLog, suppressLog,
    counts: {
      identities: identities.length, signatures: sigs.size, ...sigCounts,
      variants: design.nVar, assignments: pv.map.size,
      nC: nBucket.C, nO: nBucket.O, nP: nBucket.P, nX: nBucket.X,
      spares: spareList.length, spareList,
      designedFaces: design.nVar + sigs.size,
      reachableFaces: (design.nVar - spareList.length) + sigs.size,
      distinctEngineFaces, distinctIdentity, perSlot,
    },
    constants: {
      B_C: M.B_C, B_REF: T.B_REF, KW_SCALE: round4(M.KW_SCALE), SIG_IMPORT_SCALE: round4(M.KW_SCALE),
      S: T.S, SlotMod: T.SlotMod, R: T.R, AOE_KWB: T.AOE_KWB, COH: T.COH,
      B_CAP0: round4(B_CAP0), GENE_STEP: T.GENE_STEP, GENE_MAX: T.GENE_MAX,
      B_CAP_RUN: T.B_CAP_RUN, SPREAD_OWN: round4(SPREAD_OWN), S_MAX, G_MAX: round4(G_MAX),
      /* runtime-only knobs — engine.js reads these instead of hardcoding them (coding-standards.md) */
      SG_STEP: T.SG_STEP, SG_RBONUS: [0, 1, 1, 1, 1, 2, 2, 2],
      SG_TIER: { normal: 0, summer: 1, nightmare: 2, japanese: 3, shiny: 4, xmas: 4, meo1: 4, meo2: 4, origin: 5, mystic: 6, agamogenesis: 7 },
      SCARCITY_RFLOOR: T.SCARCITY_RFLOOR, COH_FLOOR_SECRET: T.COH_FLOOR_SECRET,
      HP_STEP: [0, 3, 5, 8, 10, 13, 15],
    },
  };
}

/* ================================================================= *
 * STAGE 8 — emit()                                                   *
 * ================================================================= */
/* Runtime bundle carrier (ADR: generated data reaches the game as a src/ module).
 *
 * build.py concatenates ONLY the files in its FILES list and never reads assets/; the game
 * ships as one self-contained HTML with no bundler and no runtime fetch. So the JSON snapshot
 * — which stays the reviewable artefact and the thing --check diffs — is ALSO emitted as
 * src/part_faces.js declaring a plain `const`, exactly the way src/art.js already carries
 * generated sprite data. Both files are written from the same object in the same run, and
 * --check byte-compares both, so a stale bundle is a RED gate, never a silent ship. */
function buildRuntimeJs(out) {
  return '/* GENERATED by tools/gen_faces.mjs — DO NOT EDIT BY HAND.\n'
    + '   Source of truth: assets/data/part_faces.json (same bytes, same run).\n'
    + '   Re-generate with: node tools/gen_faces.mjs   ·   verify with: node tools/gen_faces.mjs --check\n'
    + '   design/gdd/part-skill-identity.md §6f. Consumed by axieToDie() in src/engine.js. */\n'
    + 'const PART_FACES = ' + JSON.stringify(out) + ';\n';
}

function buildOutput(rep, engineVersion) {
  const familyVariant = {};
  for (const [id, rec] of [...rep.variantValues.entries()].sort()) {
    const { cls, slot, letter, t, k } = rec.tpl;
    familyVariant[cls] = familyVariant[cls] || {};
    familyVariant[cls][slot] = familyVariant[cls][slot] || {};
    /* `v` is the pinned value at gene 0 / coherence 1 — what reviewers read in the diff.
       `m`/`c`/`mode` let engine.js re-derive it at any other budget (gene ladder §3.4a,
       coherence §3.4b); `lift` carries the F6 monotone bump and any REPAIR bump, which are
       per-BUCKET decisions the affine model cannot know about. By construction,
       max(1, ROUND(m*B_base - c)) + lift[b] === v[b] — asserted by I28 below. */
    const B = (b) => rep.constants.B_C * rep.constants.S[b];
    const evalAff = (aff, budget) => {
      const x = aff.m * budget - aff.c;
      return Math.max(1, aff.mode === 'f' ? Math.floor(x) : Math.round(x));
    };
    const lift = {};
    for (const b of ['C', 'O', 'P']) {
      lift[b] = rec.v[b] - evalAff(rec.aff, B(b));
      if (!Number.isFinite(lift[b])) hardFail('I28', `${id}@${b}`, 'a finite monotone/repair lift', String(lift[b]));
    }
    familyVariant[cls][slot][letter] = {
      t, k, v: { C: rec.v.C, O: rec.v.O, P: rec.v.P },
      m: rec.aff.m, c: rec.aff.c, mode: rec.aff.mode, lift,
      ...(rec.sup ? { sup: { k: rec.sup.k, m: rec.sup.aff.m, c: rec.sup.aff.c, mode: rec.sup.aff.mode } } : {}),
    };
  }
  const signatureFace = {};
  for (const f of rep.sigFaces) signatureFace[f.key] = { p: f.p, t: f.t, v: f.v, k: f.k, r: f.r, src: 'sig' };
  const partVariant = {};
  for (const a of [...rep.pv.map.values()].sort((x, y) => (x.key < y.key ? -1 : 1))) partVariant[a.key] = a.letter;
  const scarcityBucket = {};
  for (const i of rep.identities) scarcityBucket[i.key] = i.bucket;
  return {
    schema: 1,
    engineVersion,
    profile: rep.profile,
    constants: rep.constants,
    familyVariant, signatureFace, partVariant, scarcityBucket,
    manifest: {
      monotoneLifts: rep.monotoneLifts,
      sigLifts: rep.sigLifts,
      spreadLog: rep.spreadLog,
      suppressLog: rep.suppressLog,
      repairLog: rep.repair.repairLog,
      clampFloor: rep.clampFloor,
      totals: {
        nSig: rep.counts.signatures, nC: rep.counts.nC, nO: rep.counts.nO,
        nP: rep.counts.nP, nX: rep.counts.nX, variants: rep.counts.variants,
        spares: rep.counts.spares, spareList: rep.counts.spareList,
        designedFaces: rep.counts.designedFaces, reachableFaces: rep.counts.reachableFaces,
        distinctEngineFaces: rep.counts.distinctEngineFaces,
        distinctIdentityFaces: rep.counts.distinctIdentity,
        perSlot: Object.fromEntries(SLOT_ORDER.map((s) => [s, {
          parts: rep.counts.perSlot[s].parts,
          distinct: rep.counts.perSlot[s].distinct,
          lost: rep.counts.perSlot[s].lost,
        }])),
      },
    },
  };
}

/* engineVersion — read from src/engine.js via the house vm loader (§6f "khớp src/engine.js:9") */
function readEngineVersion() {
  try {
    const ctx = { console, Math, JSON };
    vm.createContext(ctx);
    const src = ['src/data.js', 'src/engine.js'].map((f) => fs.readFileSync(P(f), 'utf8')).join('\n')
      + '\n;globalThis.__X={VERSION: (typeof VERSION!=="undefined"?VERSION:null)};';
    vm.runInContext(src, ctx);
    if (ctx.__X && ctx.__X.VERSION) return String(ctx.__X.VERSION);
  } catch { /* fall through */ }
  const m = /(?:VERSION|BUILD)\s*=\s*['"]([^'"]+)['"]/.exec(fs.readFileSync(P('src/engine.js'), 'utf8'));
  return m ? m[1] : 'unknown';
}

/* AC-33 — --check-citations */
function checkCitations(md) {
  const out = [];
  const re = /`?(src\/[a-z_]+\.js|api\/[a-z-]+\.js):(\d+)(?:-\d+)?`?/g;
  const cache = new Map();
  const readLines = (f) => {
    if (!cache.has(f)) cache.set(f, fs.existsSync(P(f)) ? fs.readFileSync(P(f), 'utf8').split('\n') : null);
    return cache.get(f);
  };
  const lines = md.split('\n');
  for (let i = 0; i < lines.length; i++) {
    for (const m of lines[i].matchAll(re)) {
      const [, file, numS] = m;
      const num = Number(numS);
      const src = readLines(file);
      if (!src) { out.push({ doc: i + 1, file, num, status: 'FILE-MISSING' }); continue; }
      /* find a symbol name mentioned next to the citation */
      const around = lines[i];
      const symMatch = [...around.matchAll(/`([A-Za-z_$][A-Za-z0-9_$]*)`/g)].map((x) => x[1])
        .filter((s) => s !== 'src' && !/\.js$/.test(s));
      let ok = null, found = [];
      for (const sym of symMatch) {
        const hits = [];
        for (let j = 0; j < src.length; j++) {
          if (new RegExp(`(^|[^A-Za-z0-9_$])${sym.replace(/[$]/g, '\\$')}\\s*[=:(]`).test(src[j])) hits.push(j + 1);
        }
        if (!hits.length) continue;
        found.push({ sym, hits });
        if (hits.some((h) => Math.abs(h - num) <= 3)) { ok = sym; break; }
      }
      if (symMatch.length && ok === null && found.length) {
        out.push({ doc: i + 1, file, num, status: 'DRIFT', candidates: found.slice(0, 3) });
      }
    }
  }
  return out;
}

/* ================================================================= *
 * MAIN                                                               *
 * ================================================================= */
function main() {
  const opts = parseArgs(process.argv.slice(2));
  if (opts.help) { process.stdout.write(HELP); return 0; }

  /* ---- I/O boundary: everything below derive() is pure ---- */
  const catalogRows = JSON.parse(fs.readFileSync(IN_CATALOG, 'utf8'));
  const md = fs.readFileSync(IN_DESIGN, 'utf8');
  fs.mkdirSync(path.dirname(IN_TUNING), { recursive: true });
  if (!fs.existsSync(IN_TUNING)) {
    fs.writeFileSync(IN_TUNING, JSON.stringify(DEFAULT_TUNING, null, 2) + '\n');
    finding('bootstrap', `created ${path.relative(ROOT, IN_TUNING)} from built-in defaults (§7 knobs); it did not exist`);
  }
  const T = { ...DEFAULT_TUNING, ...JSON.parse(fs.readFileSync(IN_TUNING, 'utf8')) };

  if (opts.checkCitations) {
    const drift = checkCitations(md);
    for (const d of drift) console.log(`CITATION ${d.status} doc:${d.doc} -> ${d.file}:${d.num} candidates=${JSON.stringify(d.candidates || [])}`);
    console.log(`\ncitations checked; ${drift.length} suspicious`);
    return drift.length ? 1 : 0;
  }

  if (opts.matrix) {
    const rows = [];
    for (const profile of ['reference', 'production']) {
      for (const cfg of [
        { noR7: true, noRepair: true, label: 'no R7/R8/SPREAD, no REPAIR  (tables as authored)' },
        { noR7: true, noRepair: false, label: 'no R7/R8/SPREAD, REPAIR on  (AC-9c-base pipeline)' },
        { noR7: false, noRepair: false, label: 'R7 + R8/SPREAD + REPAIR     (target state, ships)' },
      ]) {
        const before = failures.length;
        const r = derive(catalogRows, md, T, { ...opts, profile, ...cfg });
        const nFail = failures.length - before;
        failures.length = before;
        const c = r.counts;
        rows.push({ profile, label: cfg.label, distinct: c.distinctEngineFaces, ident: c.distinctIdentity,
          perSlot: SLOT_ORDER.map((s2) => c.perSlot[s2].distinct), nFail });
      }
    }
    console.log('');
    console.log('AC-9c-base MATRIX — engine-distinct (p,t,v,k) faces out of 285');
    console.log('='.repeat(126));
    console.log(`  ${'profile'.padEnd(11)}${'configuration'.padEnd(60)}${'distinct'.padStart(9)}${'ident'.padStart(7)}   ${SLOT_ORDER.map((s2) => s2.slice(0, 5).padStart(6)).join('')}`);
    console.log('-'.repeat(126));
    for (const r of rows) {
      console.log(`  ${r.profile.padEnd(11)}${r.label.padEnd(60)}${String(r.distinct).padStart(9)}${String(r.ident).padStart(7)}   ${r.perSlot.map((n) => String(n).padStart(6)).join('')}`);
    }
    console.log('-'.repeat(126));
    console.log('');
    console.log('  AC-9c-base (the pre-R7 baseline) is NO LONGER MEASURABLE: §3.11 was re-authored for');
    console.log('  R7, so the old keyword sets it counted are gone. Its last valid measurement, against');
    console.log('  the pre-consolidation tables, was 198 reference / 190 production. The doc\'s hand count');
    console.log('  for that same state was 201 (mouth 27 horn 35 back 40 tail 43 eyes 31 ears 25).');
    console.log('');
    return 0;
  }

  const snapPath = opts.profile === 'reference' ? OUT_REF : OUT_MAIN;
  if (fs.existsSync(snapPath)) {
    try { opts.prevClampFloor = JSON.parse(fs.readFileSync(snapPath, 'utf8')).manifest.clampFloor.length; }
    catch { /* unreadable snapshot: I19 simply does not run */ }
  }

  const rep = derive(catalogRows, md, T, opts);

  /* --- determinism proof (AC-1): re-run and byte-compare --- */
  const n = Math.max(0, opts.proveDeterminism | 0);
  if (n > 0) {
    const base = JSON.stringify(buildOutput(rep, 'x'));
    for (let i = 0; i < n; i++) {
      const before = failures.length;
      const again = JSON.stringify(buildOutput(derive(catalogRows, md, T, opts), 'x'));
      failures.length = before;                     // repeat runs re-report the same failures
      if (again !== base) {
        hardFail('PURITY', `run ${i + 1}`, 'byte-identical derivation', 'drifted',
          'the derivation path is not pure — replay verification would break');
        break;
      }
    }
  }

  /* --- refresh-catalog runbook (E1) --- */
  if (opts.refreshCatalog) {
    const known = new Set([...rep.sigs.keys(), ...rep.pv.map.keys()]);
    const cat = new Set(rep.identities.map((i) => i.key));
    const added = [...cat].filter((k) => !known.has(k)).sort();
    const gone = [...known].filter((k) => !cat.has(k)).sort();
    console.log(`--refresh-catalog: ${cat.size} catalog identities`);
    console.log(`  new (in catalog, not in the design tables): ${added.length}`);
    added.forEach((k) => console.log(`    + ${k}`));
    console.log(`  missing (in the design tables, not in the catalog): ${gone.length}`);
    gone.forEach((k) => console.log(`    - ${k}`));
  }

  const out = buildOutput(rep, readEngineVersion());
  const target = opts.profile === 'reference' ? OUT_REF : OUT_MAIN;
  const text = JSON.stringify(out, null, 2) + '\n';

  if (opts.check) {
    if (!fs.existsSync(target)) {
      hardFail('CHECK', path.relative(ROOT, target), 'committed snapshot exists', 'missing', 'run gen_faces.mjs and commit the output');
    } else if (fs.readFileSync(target, 'utf8') !== text) {
      hardFail('CHECK', path.relative(ROOT, target), 'byte-identical to the committed snapshot', 'differs', 'design inputs or knobs changed — re-run the generator and commit the diff');
    }
  } else if (opts.write) {
    fs.writeFileSync(target, text);
  }

  /* The production profile additionally carries the same object into the bundle (see
     buildRuntimeJs). The reference profile is an audit artefact only and never ships. */
  if (opts.profile !== 'reference') {
    const js = buildRuntimeJs(out);
    if (opts.check) {
      if (!fs.existsSync(OUT_JS)) {
        hardFail('CHECK-JS', path.relative(ROOT, OUT_JS), 'committed runtime bundle exists', 'missing',
          'run gen_faces.mjs and commit src/part_faces.js — build.py needs it');
      } else if (fs.readFileSync(OUT_JS, 'utf8') !== js) {
        hardFail('CHECK-JS', path.relative(ROOT, OUT_JS), 'byte-identical to the committed runtime bundle', 'differs',
          'the shipped bundle is STALE relative to the JSON — re-run the generator and commit both');
      }
    } else if (opts.write) {
      fs.writeFileSync(OUT_JS, js);
    }
  }

  report(rep, opts, target);

  /* Split failures into KNOWN (declared in tools/known-failures.json, with an owner and a
     reason) and NEW. Only NEW failures break the build — otherwise a single unfixed design
     defect would leave the gate permanently red and CI would stop meaning anything. A declared
     id that stops failing is ALSO an error, so fixing I18 forces the entry to be removed. */
  let allow = [];
  if (!opts.strict && fs.existsSync(KNOWN_FAILURES)) {
    try { allow = (JSON.parse(fs.readFileSync(KNOWN_FAILURES, 'utf8')).gen_faces || []); }
    catch (e) { console.log(`gen_faces: cannot read ${path.relative(ROOT, KNOWN_FAILURES)}: ${e.message}`); return 2; }
  }
  const allowById = new Map(allow.map((a) => [a.id, a]));
  const known = failures.filter((f) => allowById.has(f.id));
  const fresh = failures.filter((f) => !allowById.has(f.id));
  const firedIds = new Set(failures.map((f) => f.id));
  const stale = allow.filter((a) => !firedIds.has(a.id));

  const show = (list) => {
    for (const f of list) {
      console.log(`  [${f.id}] ${f.row}`);
      console.log(`        expected: ${f.expected}`);
      console.log(`        actual:   ${f.actual}`);
      if (f.extra) console.log(`        note:     ${f.extra}`);
    }
  };
  if (known.length) {
    console.log(`\n${known.length} KNOWN failure(s) — declared in ${path.relative(ROOT, KNOWN_FAILURES)}, not a build break:`);
    for (const a of allowById.values()) {
      const n = known.filter((f) => f.id === a.id).length;
      if (n) console.log(`  [${a.id}] x${n} — owner ${a.owner} — ${a.ref}`);
    }
  }
  if (stale.length) {
    console.log(`\n${stale.length} STALE allowlist entr(y/ies) — these invariants now PASS, remove them:`);
    for (const a of stale) console.log(`  [${a.id}] declared ${a.since} by ${a.owner} — delete it from ${path.relative(ROOT, KNOWN_FAILURES)}`);
  }
  if (fresh.length) {
    console.log(`\n${fresh.length} HARD FAILURE(S) — build gate is RED\n`);
    show(fresh);
  }
  if (opts.strict && known.length) { console.log(`\n--strict: ${known.length} known failure(s) shown in full\n`); show(known); }
  if (!fresh.length && !stale.length) console.log(`\ngate: GREEN${known.length ? ` (${known.length} known failure(s) allowed)` : ''}`);
  return (fresh.length || stale.length) ? 1 : 0;
}

function report(rep, opts, target) {
  const c = rep.counts;
  const L = (s) => console.log(s);
  L('');
  L('gen_faces — MEASUREMENT PROVENANCE (every count below is for exactly this configuration)');
  L('='.repeat(78));
  L(`  profile : ${opts.profile}  (B[C] = ${rep.constants.B_C}, SIG_IMPORT_SCALE = ${rep.constants.SIG_IMPORT_SCALE})`);
  L(`  R7/R8   : ${opts.noR7 ? 'DISABLED  — pre-R7 baseline, AC-9c-base' : 'ENFORCED  — R7 slot-wide keyword-set uniqueness'}`);
  L(`  SPREAD  : ${opts.noR7 ? 'DISABLED  — bundled with R7/R8 by AC-9c-base' : 'ENFORCED  — R8 slot-scope (§3.5d-bis)'}`);
  L(`  REPAIR  : ${opts.noRepair ? 'SKIPPED   — §3.11 columns exactly as authored' : (opts.repairAllBuckets ? 'ON (literal §3.5d, all buckets)' : 'ON (reachable (variant,bucket) instances only)')}`);
  L('='.repeat(78));
  L(`parsed: ${c.legacy} legacy sig + ${c.addendum} addendum + ${c.secret} secret = ${c.signatures} signatures`);
  L(`        ${c.variants} family variants (${c.spares} spare -> ${c.variants - c.spares} reachable)`);
  L(`        ${c.assignments} part->variant assignments`);
  L(`        ${c.identities} catalog identities   nC=${c.nC} nO=${c.nO} nP=${c.nP} nX=${c.nX}`);
  L('');
  L(`ENGINE-DISTINCT FACES (p, t, v, k) : ${c.distinctEngineFaces} / ${c.identities}`);
  L(`IDENTITY-DISTINCT     (cls,p,t,v,k): ${c.distinctIdentity} / ${c.identities}`);
  L('');
  L('  slot    parts   sig   var   distinct   lost');
  for (const s of SLOT_ORDER) {
    const p = c.perSlot[s];
    L(`  ${s.padEnd(7)} ${String(p.parts).padStart(4)}  ${String(p.sig).padStart(4)}  ${String(p.var).padStart(4)}   ${String(p.distinct).padStart(6)}   ${String(p.lost).padStart(4)}`);
  }
  L(`  ${'TOTAL'.padEnd(7)} ${String(c.identities).padStart(4)}  ${String(c.signatures).padStart(4)}  ${String(c.assignments).padStart(4)}   ${String(c.distinctEngineFaces).padStart(6)}   ${String(c.identities - c.distinctEngineFaces).padStart(4)}`);
  L('');
  if (rep.excluded.length) L(`EXCLUDED from the counts: ${rep.excluded.length} part(s) whose §3.11 row is unparseable (${[...new Set(rep.excluded.map((e) => e.variant))].join(', ')})`);
  L(`suppressLog: ${rep.suppressLog.length} replacement(s) assigned by the §3.4b SUPPRESS pass`);
  L(`spreadLog: ${rep.spreadLog.length}   ${rep.spreadLog.map((l) => `${l.name} +${l.bumps} -> ${l.v} [${l.k.join(' ')}]`).join(' · ')}`);
  L(`sigLifts: ${rep.sigLifts.length}   ${rep.sigLifts.map((l) => `${l.face.split('|').pop()} ${l.from}->${l.to}`).join(' · ')}`);
  L(`monotone lifts: ${rep.monotoneLifts.length}   clampFloor: ${rep.clampFloor.length}   repair: ${rep.repair.collisions} collision(s) resolved by bump`);
  if (opts.profile === 'reference') {
    L('AC-7 reference cell check: NOT MEASURABLE — §3.11 no longer carries C/O/P columns');
    L('   (they were removed on purpose; AC-7d --check against the snapshot is the gate now)');
  }
  if (opts.explain) {
    L('');
    L('COLLISIONS — parts that share an engine tuple with an earlier part in the same slot:');
    for (const s of SLOT_ORDER) {
      const p = rep.counts.perSlot[s];
      if (!p.collisions.length) continue;
      L(`  ${s} (${p.lost}):`);
      for (const x of p.collisions) L(`    ${x.b}  ==  ${x.a}   [${x.tuple}]`);
    }
    L('');
    L('IDENTITY-LEVEL COLLISIONS (same class+slot+t+v+k — these break AC-9b):');
    const seen = new Map();
    for (const f of rep.faces.slice().sort((a, b) => (a.partKey < b.partKey ? -1 : 1))) {
      const t = `${f.cls}|${engineTuple(f)}`;
      if (seen.has(t)) L(`    ${f.partKey}  ==  ${seen.get(t)}   [${t}]`);
      else seen.set(t, f.partKey);
    }
  }
  const seenNote = new Set();
  if (findings.length) { L(''); for (const f of findings) { if (seenNote.has(f.msg)) continue; seenNote.add(f.msg); L(`note: ${f.msg}`); } }
  if (opts.write) L(`\nwrote ${path.relative(ROOT, target)}`);
  else L(`\n(no write: ${opts.check ? '--check' : '--dry-run'})`);
}

let __code;
try { __code = main(); } catch (e) {
  console.error('\ngen_faces: FATAL — could not read the design input.\n');
  console.error('  ' + (e && e.message ? e.message : String(e)));
  console.error('\n  This usually means design/gdd/part-skill-identity.md was restructured and a');
  console.error('  parser in this file needs updating. That is intentional: the generator refuses to');
  console.error('  emit numbers it cannot derive rather than guessing.\n');
  __code = 2;
}
process.exit(__code);
